### ISSUE TITLE
Proposal: unroll attribute

### ISSUE THREAD

**Issue by FluxusMagna** [diku-dk/futhark#1062]
I propose an attribute that unrolls loops with length known at compile time. This would be useful for cases where the problem is easily defined as a loop but operates on data of a known and relatively small size.

    #[unroll]
    loop a = a' for b in bs do f b a

where `bs` has length `n`, would unroll to 
    
    a' |> f b[0] |> f b[1] |> ... f b[n-2] |> f b[n-1]

Depending on how `bs` is generated, it could also be unrolled, together with the loop, such as in the case of simple number sequence.

Since Futhark already has size-types, I think it should be relatively simple to identify such statically known lengths.

**Comment by athas** [comment]
I don't think we need to identify statically known lengths in the type system.  Instead if the loop turns out to not be unrolled (because the size turns is not static), then we should issue a warning at code-generation time, like with [this attribute](https://futhark.readthedocs.io/en/latest/language-reference.html#warn-safety-checks).  That's much simpler.

**Comment by athas** [comment]
We are not good enough at tracking source locations, so the warning will not actually tell you which loop fails to be unrolled.  Better than nothing I guess...
