### ISSUE TITLE
ROCm implementation

### ISSUE THREAD

**Issue by ShalokShalom** [diku-dk/futhark#1135]
Hi there :) 

Is ROCm something that will eventually happen?
In my limited view is OpenCL outdated and CUDA non-free.

ROCm is modern and open source

**Comment by athas** [comment]
ROCm isn't an API.  It's an implementation of various things, including (among other things) OpenCL.  Which API in ROCm do you think Futhark should target?  Futhark works quite well on top of OpenCL-on-ROCm - it's what I use on my own computer.

**Comment by ShalokShalom** [comment]
Ah, I thought its a replacement while I guess some documentation around that could work?

**Comment by athas** [comment]
I am sort of trying to stay out of trying to tell users how they should install GPU drivers and other fundamental libraries, since it's a can of worms that is highly system-specific, and can get pretty much arbitrarily complicated.  But we would not be averse to [extra information in the installation instructions](https://futhark.readthedocs.io/en/latest/installation.html#installing-futhark-on-linux).
