### ISSUE TITLE
Add support for half-precision floating point

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#116]
Deep learning seems to be all about 16-bit floating point for performance reasons.  We should also have some of that.

**Comment by oleks** [comment]
Yuck!

**Comment by nqpz** [comment]
Barf!

**Comment by Athas** [comment]
![fast](https://cloud.githubusercontent.com/assets/55833/13196545/ff17e2b2-d7d0-11e5-82f2-e239caba59be.jpg)

**Comment by oleks** [comment]
![float](https://cloud.githubusercontent.com/assets/166050/13197717/deabdd24-d7f5-11e5-98e2-88bd53af53c3.png)

**Comment by oleks** [comment]
On a more serious note, here's why it's relevant:

https://github.com/MatthieuCourbariaux/deep-learning-multipliers

Workshop paper: http://arxiv.org/abs/1412.7024

**Comment by Athas** [comment]
![sonic2](https://cloud.githubusercontent.com/assets/55833/13314228/51a24de8-dba4-11e5-9e97-4db320ac8ee4.png)

**Comment by Athas** [comment]
The big challenge here is also supporting FP16 on the CPU side.  Unfortunately, this is not a type that is supported by C, so it needs to be emulated.  I wonder if we can do it by extending to 32 bit before all operations, then round back to 16 bits at the end.  It does not have to be efficient, just sort of correct.

**Comment by ruler501** [comment]
I second this request. I think on x86 architectures the only reasonable way to handle it is to convert to and from float32 for all operations since float16 doesn't have any hardware support. I do believe there is hardware support and at least GCC supports them in the language with a flag for ARM. I personally have a program that benefits greatly from using half precision floats since they fit much nicer in memory as well as I believe take fewer cycles on Nvidia GPUs pre 30x0 series cards for most ops.

**Comment by flip111** [comment]
https://github.com/suruoxi/half/blob/master/include/half.hpp

**Comment by athas** [comment]
Is there much advantage do actually doing the computations in 16 bit on the CPU?  My plan was to use some arbitrary 16-bit type as the storage format, and then cast to 32-bit floats for all arithmetic.  I am reluctant to embed thousands of lines of code in each generated program just for 16-bit floats (and that's a C++ library too, which is a no-go).

**Comment by flip111** [comment]
that code was not meant to be included directly but to show such code can be very large. Most of it seems to be helper functions though

> My plan was to use some arbitrary 16-bit type as the storage format, and then cast to 32-bit floats for all arithmetic.

https://github.com/suruoxi/half/blob/master/include/half.hpp#L449-L568

https://github.com/suruoxi/half/blob/master/include/half.hpp#L742-L899

**Comment by athas** [comment]
Why did we never get around to doing this?  Should be easy.  Even my cheap AMD GPU supports the `cl_khr_fp16` extension, and I think it's easy to fall back to emulation on OpenCL with `#ifdef`s.  Haven't checked what it takes with CUDA.

**Comment by athas** [comment]
There are many annoying problems here.  A selection:

1. C does not have `half`, of course, but this can be worked around.
2. Oclgrind claims to support the `cl_khr_fp16` extension, but fails to generate code.
3. CUDA requires you to import a header `cuda_fp16.h` *in the device code*, which can only be found if NVRTC has been explicitly passed the location of the CUDA include path.  I wonder if the Futhark compiler should actually go looking for this directory (ew), or just pass the components of the `CPATH` environment variable as include paths.  Or maybe also look for `CUDA_HOME`, like Tensorflow?  I am extremely reluctant for Futhark to enter this insane environment variable dance, but due to NVIDIA's bad design, I'm unsure how to avoid this.

**Comment by athas** [comment]
[Apparently all of `CUDA_HOME`, `CUDA_PATH`, and `CUDA_ROOT` are used in practice](https://github.com/JuliaGPU/CUDAapi.jl/blob/master/src/discovery.jl#L214).

**Comment by namibj** [comment]
@athas 
> I am extremely reluctant for Futhark to enter this insane environment variable dance, but due to NVIDIA's bad design, I'm unsure how to avoid this.

Given the mention on the blog post that it actually just uses inline PTX, I wonder what's preventing Futhark from just emitting the inline PTX itself where it currently emits calls to Nvidia's C++ class. Because last I looked PTX was supposed to be future-proof as far as newer CUDA hardware is concerned:

[closed-source C/C++ CUDA applications are encouraged to ship both machine code (no JIT delay, and rare cases of better-than-JIT-code (like common kernels of their FFT lib and Nervana's maxas's SGEMM implementation)), as well as PTX (to run on new GPU microarchitectures without recompiling the source).]

Depending on the license of that header file, it might even be legal to just copy-paste the code manually instead of forcing NVRTC to first locate it in the file system. Can't be that hard to do without breaking anything, with how naive `#include` is.

**Comment by athas** [comment]
Nothing is preventing Futhark from doing that, and we do in fact use inline PTX elsewhere (to get the right kind of memory fence).  I'm reluctant to do that for something that will occur as frequently as half-precision floating-point operations (when they are used at all, anyway).  This is mostly out of old habit and superstition, that inline assembly tends to inhibit compiler optimisations, and we do depend heavily on the CUDA kernel compiler doing a good job, as Futhark doesn't do much scalar-level optimisation.
