### ISSUE TITLE
Why does an in-place update of a generic type fail in a loop while built-in does not?

### ISSUE THREAD

**Issue by EvilMav** [diku-dk/futhark#1171]
Consider two functions:

```futhark
let test  (n: i64) (f: i64 -> i64 -> i64) (init: i64): [n]i64 =
    loop arr = (replicate n init) for i < n-2 do
        arr with [i+2] = f arr[i] arr[i+1]

let test2 'a (n: i64) (f: a -> a -> a) (init: a): [n]a =
    loop arr = (replicate n init) for i < n-2 do
           arr with [i+2] = f arr[i] arr[i+1]
```

The first one compiles, while the second yields **"New value for elements in let-with shares data with source array.  This is illegal, as it prevents in-place modification."** error. Should not they both work the same? Is there a workaround for the second case?

**Comment by athas** [comment]
Yes, use `copy` to break the aliasing.  The reason is that when you use a polymorphic type `'a`, the compiler has no idea whether that function `f` is just going to return its first argument unchanged, which would then alias `arr`.  But it does know that integers cannot aliased, so it works in that case.  Another solution is to change the type of `f` to be `f : a -> a -> *a`, which would require that `f` always produces a *new* value that cannot possibly alias its inputs.

**Comment by EvilMav** [comment]
Thank you, this makes sense!
It does not look like the copy keyword is covered [in the reference](https://futhark.readthedocs.io/en/latest/language-reference.html).

**Comment by athas** [comment]
`copy` is not a keyword; [it's just a library function](https://futhark-lang.org/docs/prelude/doc/prelude/array.html#3680).  You can define it yourself:

```Futhark
let copy 't (a: t): *t =
  ([a])[0]
```
