### ISSUE TITLE
Overflow warning in pyopencl kernel args

### ISSUE THREAD

**Issue by EvilMav** [diku-dk/futhark#1180]
Executing `produce_a_warning.py` in the following tarball will result in a warning during kernel call:
```
em_rsj.py:5749: RuntimeWarning: overflow encountered in int_scalars
  unsign_arg_10419 = (np.int32(48271) * rnd_10413)
```
It might be related to cpprandom library use. At least for my test cases, the warning did not affect the operation of the kernel, so a minor issue.

[futhark_pyopencl_overflow.tar.gz](https://github.com/diku-dk/futhark/files/5507556/futhark_pyopencl_overflow.tar.gz)

**Comment by athas** [comment]
This is not in the kernels, but in the host code.  The overflows are harmless and intended, but I guess NumPy warns by default, since most NumPy-code probably isn't written with overflows in mind.  We already use some kind of NumPy configuration flag to disable divisision-by-zero-warnings (which are well-defined for floats), so I guess we could do the same for this...

**Comment by athas** [comment]
Oh, we already have that code, but it is only inserted for non-library entry points.  I guess that could be moved.
