### ISSUE TITLE
Unification error when unifying two sizes that are structurally equal

### ISSUE THREAD

**Issue by lalaithion** [diku-dk/futhark#1301]
I've tried to find a minimal reproduction of this but the minimal reproductions all typecheck, so this might be a weird interaction with another part of the compiler, or a bug in my code.

Here's the error:

```
Cannot apply "sample_perlin_octaves" to "(gen_perlin_octaves 2 5 (from_seed 12))" (invalid type).
Expected: {octaves: [n₀]{subdivs: i64, vecs: [m₁][m₁](f32, f32)}}
Actual:   {octaves: *[5]{subdivs: i64, vecs: [ret₅][ret₆](f32, f32)}}

Dimensions "ret₅" and "ret₆" do not match.
When matching types of record field "octaves.vecs".

Note: "ret₅" is unknown size returned by "gen_perlin_octaves" at 124:66-102.

Note: "ret₆" is unknown size returned by "gen_perlin_octaves" at 124:66-102.
```

This makes no sense, because we have

```
type perlin_octaves [o] [n] = {
  octaves: [o](perlin_noise [n])
}
```

and 

```
type perlin_noise [n] = {
  vecs: [n][n]vec,
  subdivs: i64
}
```

With the functions 

```
let gen_perlin_octaves (start_amplitude: i64) (num_amplitudes: i64) (rng: minstd_rand.rng) 
  : perlin_octaves [num_amplitudes] [] = ...
```

and 

```
let sample_perlin_octaves [n] [m] (octaves: perlin_octaves [n] [m]) (persistence: f32) (pt: (f32, f32)): f32 =  ...
```

Clearly, `ret₅` and `ret₆` are structurally the same size. There's no way to instantiate a type where they're different, because they originate from the same type variable. However, the compiler seems to forget they're the same, and then throw an error when we try to unify them.

Full code: https://gist.github.com/lalaithion/1505cbe86e450bf1ce9fc8e36a7b9b13
Attempted minimal case that still works: https://gist.github.com/lalaithion/cdf5817a6caabb291ab195731e25b9bc

**Comment by athas** [comment]
I think this is a somewhat exotic edge case that arises from Futhark's types being purely structural.  If we take the type 

```
let gen_perlin_octaves (start_amplitude: i64) (num_amplitudes: i64) (rng: minstd_rand.rng) 
  : perlin_octaves [num_amplitudes] [] = ...
```

and we inline the definition of `perlin_octaves`, then we get

```
let gen_perlin_octaves (start_amplitude: i64) (num_amplitudes: i64) (rng: minstd_rand.rng) 
  : {octaves: [o](perlin_noise [])} = ...
```

and then we inline `perlin_noise`, giving:

```
let gen_perlin_octaves (start_amplitude: i64) (num_amplitudes: i64) (rng: minstd_rand.rng) 
  : {octaves: [o]({vecs: [][]vec,subdivs: i64})} = ...
```

and then it's clear that it doesn't understand that the two anonymous dimensions are the same.

But this is a bit dumb.  I wonder if we can fix it without totally overhauling parts of the type checker.  Maybe we can change the type checker's internal representation of evaluated types such that anonymous/empty dimensions still have identity to them.  This would also let us say things like

```
type square [n] t = [n][n]t
```

which currently suffers from the same problem when you say `square []`.  This would make type abbreviations *slightly* magical, but I don't think any users would complain.

*Semantically*, a function type like the above should *really* be something like

```
let gen_perlin_octaves (start_amplitude: i64) (num_amplitudes: i64) (rng: minstd_rand.rng) 
  : ∃n.{octaves: [o]({vecs: [n][n]vec,subdivs: i64})} = ...
```

which is really what we are trying to encode, but without the explicit existentials.  I'm not ready to add explicit existentials (partially because I can't come up with a good syntax, and partially because I want to add dependent products at the same time), but we can maybe extend our handling of type abbreviations as a first step.

**Comment by lalaithion** [comment]
That makes sense, although I'm slightly confused as to why my minimal reproduction compiles, then. (Probably because it's simple enough for the type inference engine to realize that the two values are, in fact, equal).

I imagine that this could be fixed by instantiating the anonymous sizes before structural expansion, as opposed to after. This would mean that instead of trying to unify `[m₁][m₁](f32, f32)` with `[ret₅][ret₆](f32, f32)`, it would have `[ret₅][ret₅](f32, f32)`, which would succeed.

For a workaround, in case anyone else comes across this bug, I can just pass the expected size in as a parameter, and have a runtime size assertion validate the correctness. Is there a more elegant way to do this?

```
let gen_perlin_octaves (n: i64) (start_amplitude: i64) (num_amplitudes: i64) (rng: minstd_rand.rng) : perlin_octaves [num_amplitudes] [n] = 
   ...
```

**Comment by athas** [comment]
> I'm slightly confused as to why my minimal reproduction compiles, then.

Since `complicated_meta` isn't a function, the type checker happily infers its type to be `meta_sizetwice [2]`.

> I imagine that this could be fixed by instantiating the anonymous sizes before structural expansion, as opposed to after.

Yes, that would be the solution.  It's a little more tricky, because "expansion" is more like "evaluation" (type expressions are a different representation than the semantic type objects that type inference actually uses), and we'd have to worry about conflicts/capture when doing substitution.  It can probably be solved.

> For a workaround, in case anyone else comes across this bug, I can just pass the expected size in as a parameter, and have a runtime size assertion validate the correctness. Is there a more elegant way to do this?

No, that's the standard way to work around this and similar holes in size typing.

**Comment by athas** [comment]
This is actually an interesting problem that can be solved nicely, and which is relevant to the research I've been doing with @melsman recently.  I think it is time to start considering explicit existentials in Futhark types.  A function such as the above should really be considered as (and optionally written as):

```
let gen_perlin_octaves (start_amplitude: i64) (num_amplitudes: i64) (rng: minstd_rand.rng) 
  : ?n.perlin_octaves [num_amplitudes] [n] = ...
```

where we use `?` as an existential quantifier because I don't like Unicode syntax (also, I think using the dot there will cause some lexer issues).  I'm reluctant to do it as a quick hack and I have lots of other things on my plate the next few weeks, so it'll probably take a little while to get it done.

**Comment by athas** [comment]
OK, maybe I'll hack it a bit in the short term, just to get some experience with this idea of handling existentials in a more clever way.
