### ISSUE TITLE
Problems with trace and break

### ISSUE THREAD

**Issue by mortvest** [diku-dk/futhark#1355]
Neither **trace** or **break** work as intended with  <|, |>, <-<  or >-> operators.
- **trace** does not print the correct line/char number. Prints /prelude/functional.fut:.... [instead](https://gist.github.com/mortvest/3950e06b0ef3a6236345fdd3e5dbe724)
- **break** behaves very strangely. Breakpoint is recognized, but with a scope consisting of a single variable "x" (even when there are no variables called "x" in the entire [program](https://gist.github.com/mortvest/091b715e424b58a10597de238a70f839)).

Moreover, **break** is ignored when it is a part of a let-binding in a [program](https://gist.github.com/mortvest/edfa9e1e0f514f065aba7811383c6b16). Here, if you just load the file, nothing would happen.

**Comment by athas** [comment]
Interestingly, that `trace` behaviour is arguably correct, since it is printing the point where the `trace` function is invoked (even if that is not where the name is instantiated).  I'm not sure how easy that would be to change.  Do other languages with higher-order functions do this better?  I think the `break` behaviour is for the same reason (it breaks inside the definition of `|>`).  As a workaround, eta-expand to use `(\x -> trace x)` instead of just `trace` (and similarly for `break`).

The lack of `break` in top-level definitions is more or less intentional behaviour, in that we disregard breakpoints when loading the program.  This may not be *desired* behaviour, though.

**Comment by mortvest** [comment]
The workaround works, but it would be nice if it worked without it. These operators can really save lots of time in a long debugging session since they make it faster to add/remove the trace calls.

**Comment by athas** [comment]
I am now leaning towards making the workaround essentially mandatory by switching to attributes for tracing, which will syntactically require `(\x -> #[trace] x)`.  More awkward to type, but harder to do the wrong thing by accident.

**Comment by mortvest** [comment]
This definitely becomes more awkward to type, but maybe it is worth it. Btw, couldn't this approach be extended by adding arbitrary strings to the trace tag? Something like `(\x -> #[trace(debug message)])`

**Comment by athas** [comment]
Yes, that would be straightforward enough.
