### ISSUE TITLE
Add support for trace in C backend

### ISSUE THREAD

**Issue by Munksgaard** [diku-dk/futhark#1357]
While tracing in OpenCL might be difficult to do, it should be pretty straightforward in the C backend, right?

Perhaps we could even add support for breaks, by hooking up to GDB?

**Comment by athas** [comment]
`break` would not be very useful without also recording some kind of association between the original program and the generated code.

`trace` is more plausible, but what would it look like in the core IR?  Like `opaque`?  That might be fine, but it means using `trace` can inhibit optimisations.  Another problem is that it might be difficult to assemble a prettyprinted value representation from the core value representation.  Not *impossibly difficult*, but a substantial project.  You could of course just print whatever the core representation happens to be, and let the user worry about decoding it.

**Comment by Munksgaard** [comment]
I don't think it's a problem for trace to inhibit optimizations. It would mostly be used to figure out logic bugs in user-code, not in the generated code, I think. Personally, I might try to use it in cases where the repl doesn't suffice (when working with very large arrays, for instance).

Printing the core value representation might be okay, for now. I agree that it would be difficult to recreate the source language representation (how to do that for arrays of tuples, for instance?).

**Comment by athas** [comment]
I have a simple prototype for this.  It's not difficult to add, at least not for scalars.  It's difficult to provide either a source location or the original expression of the trace, though.  I think it might be good to add a function

```
val tracemsg '~a : []u8 -> a -> a
```

where the first argument is a string that is prefixed to the output; e.g: `tracemsg "foo" x`.  This would also indirectly fix #1355, which is really annoying to improve otherwise.   We could of course also replace the type of `trace` entirely with this definition.

**Comment by athas** [comment]
Alternatively, we could use attributes instead: `#[trace] x`.  This makes it easy to find the source location.  It doesn't work within pipelines, however.
