### ISSUE TITLE
In-place update of array gives cryptic error messages

### ISSUE THREAD

**Issue by TobiasRoikjer** [diku-dk/futhark#1381]
While likely wrong, when updating arrays in place the errors messages are hard to understand. An example is this
```{futhark}
foldl (\a x -> let a[x]=a[x]+1 in a) (replicate 3 0) [1,0,0,1,2,2]
```
Gives 
```
source "a" has type [dim_5]src, which is not unique
```

The code is probably wrong, but it is hard to see why

**Comment by athas** [comment]
This error is not great, but what should it say?  I can imagine the following practical improvements:

* Mention using `copy` as a workaround (but note that this will change the asymptotics).
* Mention that since `a` is a function parameter, the programmer could add a type annotation to the parameter to make it unique.  This program still wouldn't work, as you would not be allowed to pass such a function to `foldl`.  I don't know if the error message would be better.

**Comment by TobiasRoikjer** [comment]
Is it possible to type annotate the behavior defined in https://futhark-lang.org/examples/histograms.html?
```
for j < length is:
  i = is[j]
  a = as[j]
  if i >= 0 && i < length dest:
    dest[i] = f(dest[i], a)
```

**Comment by TobiasRoikjer** [comment]
Alternatively, perhaps the error should say exactly what is wrong? That it cannot determine the size at compile time and therefore the index may be OOB (which I assume is happening). Therefore the index must either be fixed or the use of copy may be used.

It might be nice if there would ever be a feature that declared a minimum size of an array as its type, depending of course on the performance increase. (likewise to have computed array/return sized from size parameters)

**Comment by athas** [comment]
The error does say exactly what is wrong: the type of the array is not a unique type, so it cannot be used for in-place updates.  The problem is that most programmers do not understand uniqueness types, as they are an exotic feature not found in most other languages.  It does not have anything to do with the size of the array.

**Comment by TobiasRoikjer** [comment]
@athas I think then, perhaps, the solution could be to point to a Futhark article about uinque types, and how to use them?

**Comment by athas** [comment]
It's a possibility, but I don't think it's practical to turn every type error into a tutorial.

Rust has a nice model where each form of type error is connected to a page in the documentation that describes that class of errors.  It would be nice to do something similar for Futhark, but it requires a lot of effort.

**Comment by TobiasRoikjer** [comment]
That is true. Perhaps make an article on the website called e.g. Unique types in Futhark with examples and explanations. Then the error will at least be googlable.
