### ISSUE TITLE
Sum type in module implementing module type causes unification error

### ISSUE THREAD

**Issue by Programmerino** [diku-dk/futhark#1562]
When using a sum type defined in a module implementing a module type, the sum type is not considered to be a sum type by outside code. I'm assuming this isn't expected behavior. I tested this on versions `0.21.0` and the latest git master `c36f6fb29ec620ba1947f1f6169ee80d6f042fa5`.

Failing code:
```futhark
module type ModType = {
  type t
}

module OptionMod: ModType = {
    type t = #some i64 | #none
}

let wrap (x: i64): OptionMod.t =
    #some x
```
Compiler error:
```
Error at issue.fut:10:5-11:
Function body does not have expected type.
Expected: OptionMod.t
Actual:   t₀

Cannot unify a sum type with a non-sum type

If you find this error message confusing, uninformative, or wrong, please open an issue:
  https://github.com/diku-dk/futhark/issues
```

**Comment by athas** [comment]
This is by design.  In contrast to SML (and maybe OCaml, not sure), module ascriptions in Futhark are always considered opaque, so all types become abstract.  If you want the definition of the type to be visible, you need to refine the module type:

```Futhark
module OptionMod: ModType with t = #some i64 | #none = ...
```

Of course this is very verbose, so what I usually do is define the type abbreviation outside:

```Futhark
type maybe_i64 = #some i64 | #none
module OptionMod : ModType with t = maybe_i64 = {
  type t = maybe_i64
}
```

**Comment by Programmerino** [comment]
Makes sense, thank you!
