### ISSUE TITLE
Internal compiler error: The target of an Update must not alias the value to be written.

### ISSUE THREAD

**Issue by PhilipBorgesen** [diku-dk/futhark#1615]
I got the following internal compiler error with Futhark v0.21.7:
```
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
Type error after pass 'Inline conservatively':
In function entry_main
When checking function body
In expression of statement
  {main_res_4566 : ({}, [3i64]i32)}
Type error:
The target of an Update must not alias the value to be written.
```
A reduced program that causes the error is:
```
def main (A: *[3]i32) : *[3]i32 =
  let x = (opaque A)[1]
   in A with [1] = x
```

**Comment by athas** [comment]
This one is difficult to fix because it is related to a limitation in our alias tracking that is used to work around the issue in #803.  In the core language, the results of functions never have aliases.  The solution is to put some kind of alias annotation on function types in the core language, but that's a whole bunch of work.

**Comment by athas** [comment]
Oh, actually I suppose that since the workaround is in the type checker, it's not really a problem to fix it properly elsewhere.
