### ISSUE TITLE
Loop unrolling seems to cause massive code size increase and slow compilation.

### ISSUE THREAD

**Issue by luleyleo** [diku-dk/futhark#1712]
I am implementing a set of 24 mathematical functions in Futhark, which I want to evaluate in batches.

For this purpose, I've added a batch version of each function, which in turn just calls the regular function for each input. This is what it looks like for example:
```futhark
entry sphere (x: [][]f64) (xopt: []f64) (fopt: f64): []f64 =
    x |> map (\x -> bbob.sphere x xopt fopt)
```
Where the `bbob` module contains the actual implementation.

If I do this though, my compilation is suddenly **much** slower, and when I try to create a `futhark_context`, it takes about 90 seconds instead of just 5! I took a look at the generated code using `futhark dev --gpu` and the batch version generates 3 times as much code. The generated code looks like the entire inner function (`bbob.sphere`) gets embedded multiple times into the batch version.

Note that this issue only happens when targeting OpenCL or CUDA. The large amount of code not only slows down the Futhark compiler, but also the kernel compiler (IGC with OpenCL). The C or Multicore backends seem not to be affected as much.

Is there a better way to do batch evaluation, or to prevent this inlining?

**Comment by athas** [comment]
Does the `bbob.sphere` function contain parallelism?  If so, the the reason is because of *incremental flattening*; Futhark's compilation scheme for nested parallelism in the GPU backends.  The problem it tries to solve is that there is no universally *best* to map nested parallelism to a GPU, so the compiler generates multiple versions (up to three per level of nesting) and picks the best one at runtime, based on the input sizes observed.

If you *know* that this `sphere` function will always be called on a big input and that there is no need to exploit any *nested* parallelism, then you can add an attribute:

```Futhark
entry sphere (x: [][]f64) (xopt: []f64) (fopt: f64): []f64 =
    x |> map (\x -> #[sequential] bbob.sphere x xopt fopt)
```

Futhark generally has a problem with code blowup that we need to address in some manner eventually, but perhaps this can serve as a workaround.

**Comment by luleyleo** [comment]
I did some testing with all three sequential annotations, and they do help, even though it still causes overhead on my laptop with OpenGL. On my desktop with Cuda it works fine. Interestingly, they sometimes significantly improved performance, but I'll have to do more testing with this.

For now, it should be fine, but I think I'll have to get back to this later.
