### ISSUE TITLE
"Entry point functions may not be polymorphic."

### ISSUE THREAD

**Issue by quentinemusee** [diku-dk/futhark#1778]
Hello.

I got this error when trying to implement the first function of the exercice 3: "Entry point functions may not be polymorphic.".
My function is correct and is able to be called through the "main" default entry, but I cannot neither create any entry point nor using "entry" instead of "def" in the function declaration.

If I write my message here, this is because this error message doesn't exist on the internet, and is not even referenced in the Compiler Error Index (here: https://futhark.readthedocs.io/en/latest/error-index.html).

(Remind: the function header is: `entry segscan [n] 't (op: t -> t -> t) (ne: t) (arr: [n](t, bool)): [n]t = ...)`.

Thanks you in advance!

**Comment by athas** [comment]
Your function is polymorphic because it has a type parameter (`'t`).  Those are fine inside Futhark, but you cannot expose them to the outside world as entry points, as the outside world has no way of instantiating them.

For testing, the solution is to define monomorphic (and first-order) entry points: `entry test_segscan_i32 =  segscan (+) 0i32`

**Comment by quentinemusee** [comment]
Thanks you so much for answering, it totally makes sens!
