### ISSUE TITLE
In-place update for array of dimension greater than one

### ISSUE THREAD

**Issue by leonardschneider** [diku-dk/futhark#1802]
Is there a way to do an in-place update for array of dimension greater than one? I can't find one. This is also a problem for nested records.

My failed attempts:
```
[11]> let a = replicate 2 (iota 2)
[12]> a
[[0, 1],
 [0, 1]]
[13]> let a = a with [1,1] = 42
Would consume variable "a", which is not consumable.

For more information, see:
  https://futhark.readthedocs.io/en/v0.22.5/error-index.html#not-consumable
[14]> let a = a with [1] = a[1] with [1] = 42
Source array for in-place update
  a
might alias update value
  a[1]
Hint: use "copy" to remove aliases from the value.
[15]> 
```

**Comment by athas** [comment]
The reason this doesn't work for you is that in-place updates are not allowed for top-level constants (since they might be updated multiple times).  You'll need to use a `copy` to make it non-local:

```
let a = copy a with [1,1] = 42
```

That's rarely an issue in real programs, because you tend to work with function parameters rather than constants.

**Comment by leonardschneider** [comment]
Thanks for the feedback. I may have oversimplified my original issue. My array is nested in a record. I get errors like the following:
```
[33]> let a = {p=(replicate 2 (iota 2))}
[34]> let a = copy a with p = (a.p with [1,1] = 42)
Would consume variable "a", which is not consumable.

For more information, see:
  https://futhark.readthedocs.io/en/v0.22.5/error-index.html#not-consumable
```

**Comment by Munksgaard** [comment]
Are you saying that you want a function like this, but without the copy?

```futhark
def set_1_1 (a: { p: [][]i64 }) =
  let p' = copy a.p with [1,1] = 42
  in a with p = p' -- how to avoid this copy?
```

**Comment by Munksgaard** [comment]
If you specify that `a` should be unique, the copy is optimized away by the compiler:

```futhark
entry set_1_1 (a: *{ p: [][]i64 }) =
  let p' = copy a.p with [1,1] = 42
  in a with p = p'
```

Note the asterisk on the function parameter.

**Comment by leonardschneider** [comment]
Thanks. Although this is not very explicit, at least there is way!

**Comment by athas** [comment]
Yeah, these kinds of updates of deeply nested arrays and records are notationally somewhat cumbersome, because the type checker does not track aliases per "component" (this would in general not be sound).  Fortunately they are not terribly common.  I'd like to come up with an improvement, but it's not clear what it should be.
