### ISSUE TITLE
Inconsistent uniqueness handling for record type

### ISSUE THREAD

**Issue by leonardschneider** [diku-dk/futhark#1816]
I came up with the following issue, which is puzzling. Adding a field to a record raises an issue about uniqueness. Here is a simplified example in the repl.

```
Version 0.22.5.
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.

Run :help for a list of commands.
[0]> type rec1 = {x: i32}
[1]> let mod1 (r: *rec1): *rec1 = r
[2]> type rec2 = {x: [2]i32}
[3]> let mod2 (r: *rec2): *rec2 = r
[4]> type rec3 = {x: [2]i32, y: i32}
[5]> let mod3 (r: *rec3): *rec3 = r
Unique-typed return value is aliased to "r", which is not consumable.

For more information, see:
  https://futhark.readthedocs.io/en/v0.22.5/error-index.html#return-aliased
```

**Comment by athas** [comment]
Very strange; I am pretty sure I have written code similar to this before.

**Comment by leonardschneider** [comment]
That was a very quick turnaround! It seems there is another corner case though. Here is a simplified example on the latest head version.

```
Version 0.23.0.
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.

Run :help for a list of commands.
[0]> type rec [n] = {x: i32, xs: [n]i32, y: i32, ys: [n]i32}
[1]> let mod [n] (r: *rec [n]): *rec [n] = r
A unique-typed component of the return value is aliased to some other component.

For more information, see:
  https://futhark.readthedocs.io/en/latest/error-index.html#unique-return-aliased
[2]> type rec [n] = {x: i32, xs: [n]i32, y: i32}
[3]> let mod [n] (r: *rec [n]): *rec [n] = r
[4]>
```

**Comment by athas** [comment]
Unfortunately, that type error is more or less by design.  We track aliases at the granularity of bound names (for simplicity, including when explaining errors to users) and so we have no way to distinguish different parts of that record `r`.  However, we *also* don't track aliases for records as a whole, only its components, so essentially each of the three fields of `r` alias the entire variable`r`, which means you cannot possibly return it.

It's a strange corner of the type system, and you can sort of work around it by using an opaque type (via the module system) to hide that you have a record at all, which will then make the alias tracking happen at the top level of the type.  It is possible we should simply track aliases for records as a whole.  It is also possible we should track aliases for fields of records as well, rather than insisting on only tracking them for bound variable names.  Currently I suppose we are a bit inconsistent in that we do both.
