### ISSUE TITLE
More flexibility in futhark pkg paths

### ISSUE THREAD

**Issue by poeface** [diku-dk/futhark#1835]
Currently, futhark pkg places very specific constraints on the urls of packages which it adds. Currently, only packages which are:

- on github or gitlab
- public

are permitted. Additionally, the urls themselves are quite strict. At my institution, we have our own instance of gitlab hosted locally. In our set up, repos are grouped which results in urls that may contain more than just the user/organization name. For example:

https://hostname.com/organization/collection/futhark-package.git

A complimentary limitation is the requirement that packages be hosted publicly. When I tried to move a package to a github url but kept private, I still couldn't use futhark pkg.

Removing either one of these constraints help our use case quite a bit.

Thanks!

**Comment by athas** [comment]
Since our package manager is based on Go's, I took a look at how they handle private repositories.  It's a bit messy, and involves changing the user's Git configuration file to rewrite `https://` URLs to `ssh://`.  Ugh.

I think a general solution here would be to teach our package manager to handle package paths ending in `.git` (or maybe all package paths not recognised as GitHub or GitLab URLs) as Git repositories, and use `git` commands to do *all* interaction.  Currently we only support GitHub and GitLab, because we use `curl` to fetch tarballs and other information from GitHub and GitLab's web frontends.  This is mostly an optimisation - we need no information that is not available in the repository itself.  This means our package manager would do a *lot* of Git operations for `futhark pkg sync` and `futhark pkg upgrade`, and in particular that we would need to fetch entire Git repository histories.  This is probably *fine* for now, as most Futhark libraries are relatively tiny, and can be optimised later.  (Go optimises this by having a central cache of known packages alongside package versions and zipballs.)

So the question becomes, given a package path of `example.com/foo/bar/baz.git`, how can we turn that into something we can pass to `git clone`?  Would it be OK to simply prepend `https://`, and then assume that the user has configured their `git` correctly in case this is a private repository?  Personally, I exclusively use SSH-based access to private repositories, but I suppose this isn't the end of the world.

I would really like the property where if you have a setup that allows you to `git clone` a repository (private or public), then `futhark pkg` can also interact with it.  That means users will not have to learn something new.

**Comment by poeface** [comment]
> I would really like the property where if you have a setup that allows you to `git clone` a repository (private or public), then `futhark pkg` can also interact with it. That means users will not have to learn something new.

This would definitely solve my current situation.

> So the question becomes, given a package path of example.com/foo/bar/baz.git, how can we turn that into something we can pass to git clone? Would it be OK to simply prepend https://, and then assume that the user has configured their git correctly in case this is a private repository? Personally, I exclusively use SSH-based access to private repositories, but I suppose this isn't the end of the world.

If `futhark pkg` really did just use git operations under the hood, then people who want to clone from private repositories could just be on their own recognizance to enter a username and password when prompted. That would work fine for us.

Thanks for being so responsive!

**Comment by poeface** [comment]
Alright makes sense, thanks!

**Comment by Munksgaard** [comment]
> I think `futhark pkg` will always run `git` in noninteractive mode

Perhaps that could be triggered via some flag? There's no reason why we can't have both?

**Comment by Munksgaard** [comment]
> in particular that we would need to fetch entire Git repository histories

You can download a shallow copy with git, I'm pretty sure.

**Comment by athas** [comment]
> Supposedly that could be triggered via some flag? There's no reason why we can't have both?

It is better to take the right decision once and for all than to push it on the user, who might make the wrong decision.

>You can download a shallow copy with git, I'm pretty sure.

We need the history to find the `futhark.pkg` contents for every version.

**Comment by athas** [comment]
I am working on this now.  Feels pretty straightforward.  It is possible that some package operations will be slightly slower than before (since we will always checkout repositories), but I doubt it matters.  Go addresses this by having a central cache that can be accessed over the web, but that is too much infrastructure for us.

Incidentally, this will also fix  #1743.
