### ISSUE TITLE
Empty context at breakpoints with `#[break]` attribute

### ISSUE THREAD

**Issue by nbos** [diku-dk/futhark#1848]
Following the example from https://futhark-lang.org/blog/2018-09-16-the-futhark-debugger.html:
```
let main (xs: []i32) = map (\x -> #[break] x + 2) xs
```
breaks fine when evaluating `main [1,2,3]`, but inspecting the context doesn't work:
```
[0]> :l test.fut 
Loading test.fut
[0]> main [1,2,3]
Breakpoint at test.fut:5:37-50
-> #0  /prelude/soacs.fut:51:3-24
   #1  test.fut:5:26-54
   #2  [0]> :1:1-12

<Enter> to continue.
[1]> x
Unknown name "x"
[2]> 
```
It works fine if `#[break]` is replaced by (deprecated) `break` function.

**Comment by nbos** [comment]
Also, this is perhaps intended (but unintuitive?) behavior, but setting a constant `let ys = main [1,2,3]` in the file bypasses the break completely on loading the file.

**Comment by athas** [comment]
This somewhat quirky behaviour is because it is difficult to come up with a semantics that works both with `break` as a function and as an attribute.  If we use something that works well as a function, then it will break *inside* the `break` function itself, which is not terribly useful.  Currently the semantic is to always pop off a single stack frame, which makes the `break` function work sensibly, but results in the behaviour you notice for the attribute.  I wonder if we should perhaps just special case the `break` prelude function in the interpreter.

> Also, this is perhaps intended (but unintuitive?) behavior, but setting a constant let ys = main [1,2,3] in the file bypasses the break completely on loading the file.

This is intentional.  Breakpoints in constants are ignored when loading the file.  I supposed that can be changed if this behaviour is undesirable.
