### ISSUE TITLE
Overconstrained size types in repeated operator pattern

### ISSUE THREAD

**Issue by poeface** [diku-dk/futhark#1850]
Hello again! I am receiving a compile error that doesn't seem right for the following program:

```
let matmul_i32 [n][m][p] (A: [n][m]i32) (B: [m][p]i32) : [n][p]i32 =
    map (\A_row -> map (\B_col -> reduce (+) 0 (map2 (*) A_row B_col)) (transpose B)) A

entry main (x: i32) =
    let n = 10
    let m = 1
    let A = tabulate_2d n n (\i j -> i32.i64 (i+j))
    let B = tabulate_2d n n (\i j -> i32.i64 (i+j))
    let C = tabulate_2d n m (\i j -> i32.i64 (i+j))
    let (*) = matmul_i32
    in A * B * C --doesn't work
    -- in A * (B * C) --works
```

The compiler complains:

```
Error at bug1.fut:13:16-16:
Cannot apply "*" to "C" (invalid type).
Expected: [n][n]i32
Actual:   [n][m]i32

Dimensions "n" and "m" do not match.
```

The problem is fixed if the final expression A * B * C is replaced with A * (B * C).

Without knowing the internals of the futhark compiler, my best guess is that the pattern `prod -> pow ("*" pow)*` is being used to parse the final line of the above program, instantiating `*` with a single (size) type. Hence the parentheses fix the problem by requiring the parser not to "combine" these `*`. This might not be technically wrong, but it is probably unintuitive for the typical user.

here is the code: [bug1.zip](https://github.com/diku-dk/futhark/files/10457919/bug1.zip)

My guess is this issue falls somewhere between bug and enhancement.

**Comment by rowanG077** [comment]
I'm not so sure this is a bug. `matmul_i32` is not associative so `A * B * C` is ambiguous since `(A * B) * C /= A * (B * C)`.  Haskell for example also defaults from left to right.

**Comment by rowanG077** [comment]
Ah yeah I'm totally wrong. This is a bug 🤦

**Comment by athas** [comment]
The problem is that the local definition `let (*) = matmul_i32` produces a *monomorphic* function.  The first time you apply it, you fix exactly the sizes you want it to accept.  Only top level definitions and definitions with function parameters are generalised in Futhark's type system.  The justification for this is discussed [in this paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tldi10-vytiniotis.pdf), but it basically boils down to producing better type errors in the common case, at the cost of more typing in the uncommon case.

The workaround is to declare `*` as a top level function.  Normally you could also define it as a local function, e.g.

```
let (*) x y = matmul_i32 x y
```

but it turns out we don't allow locally defined infix operators (for no good reason; that can be fixed).
