### ISSUE TITLE
plot-bench.py: histogram improvements

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#1886]
![image](https://user-images.githubusercontent.com/55833/223433392-ba28b03a-8ccf-49eb-a76a-09689f7b746f.png)

* I think the y axis label should be "density", not "probability".

* The x axis having a lower bound of 0 is not good, as seen here:

![image](https://user-images.githubusercontent.com/55833/223433723-df3e4965-22c6-4546-abff-18b3d6ebf787.png)

It is completely impossible to see what the actual distribution is.

**Comment by FluxusMagna** [comment]
I think labeling/scaling the y-axis is a bit problematic since the integral of the function should be equal to 0. Using the time scale it is of course possible to set it by some numerical integration of the data, but I'm not sure of how great value the scale would be.

In some ways a cumulative distribution function  would make more sense to plot, since it always goes between 0 and 1.

**Comment by athas** [comment]
I don't understand why re-labelling the y-axis would be a problem (and the scale is fine).

A cumulative distribution graph might be useful, though.

**Comment by FluxusMagna** [comment]
Since it's the integrand, the unit would be 1/s, and the amplitude would depend hugely on the overall runtime variance, without any consideration of the relative deviation. It would not be completely useless, but for comparison between processes of different average runtime, the number itself will not be very useful for comparing the two. Perhaps I'm just not seeing the actual purpose of this type of plot. 

Say for example that we have the same process running on different hardware. The runtime distribution looks the same, except stretched out for the slower case. In this type of plot the scaling on both the x-axis and y-axis need to change, but in a cumulative plot, only x-axis scaling would change, making comparison easier.

Another reason to prefer a cumulative plot is that we are pretty poor judges of the area under a spike in a plot like this(which is what the quote is about).  Spikes that are visually similar can differ a fair bit in terms of the number of values they represent. In this sense a bar-plot would be a better way to represent the bins.

**Comment by athas** [comment]
The purpose of these plots is mostly to see whether something fishy is going on, e.g. two peaks where the average is in the middle, which probably suggests that some bistable phenomena like frequency stepping or overheating cycles is happening.  It is mostly for internal use by compiler hackers when investigating performance on new hardware.

**Comment by FluxusMagna** [comment]
I guess if it's for purely qualitative observation, the scale does indeed not matter. I've previously worked with data where this type of plotting can obscure important quantitative information, but that's probably not the case here then.

**Comment by athas** [comment]
The plot is also not going to stand by itself.  There are three other plots of the same underlying information, that together (hopefully) paint a full picture.

**Comment by FluxusMagna** [comment]
Another option would be convolving the unbinned data with a gaussian kernel. This gives a smooth curve that looks like a better(or at least prettier) estimate of the underlying distribution. The size of bins/kernels should probably be determined by the sample variance and number of samples, so that each point in the plot is not to noisy.
