### ISSUE TITLE
Original array after map needs to be unique for in-place updates

### ISSUE THREAD

**Issue by Programmerino** [diku-dk/futhark#1941]
I'm having trouble with the following code:
```futhark
def test (arr: []i64) =
    let entries = arr |> map(\_ -> 0)
    in entries with [0] = 0
```
with error:
```
Error at test.fut:3:8-27:
Consuming "arr" which is a non-consumable parameter bound at test.fut:1:11-13.
If you find this error message confusing, uninformative, or wrong, please open an issue:
  https://github.com/diku-dk/futhark/issues
```

This behavior doesn't make a lot of sense of me, since the function signature for `map` doesn't require a unique array.

I tested this on `0.24.3` and the latest commit

**Comment by athas** [comment]
This is an unfortunate consequence of our inability to reason about aliasing for polymorphic functions.  The value returned by `|>` will alias both of its arguments.  In this case, `entries` aliases `arr`.  This is sensible for something like `arr |> id`, but is a conservative over-estimate when the right-hand function returns a fresh array.  In principle fixing this is possible and might even be an interesting paper, but the downside is that *every* higher-order type will be made much more complicated as it needs to explain how the aliasing of the arguments affects the aliasing of the result.

In this case, the workaround is to use `copy entries with [0] = 0`.  This does not affect the asymptotics of the program, since the `map` is O(n) work already, and the optimiser is very likely to remove the `copy` anyway.

**Comment by Programmerino** [comment]
Thank you for explaining! I will just use a `copy` then...
