### ISSUE TITLE
failed when use futhark on windows

### ISSUE THREAD

**Issue by wujilingfeng** [diku-dk/futhark#1948]
I downloaded the compiled futalk under Windows. And I  installed the cuda and mingw on windows, 
When I run `futhark.exe cuda fact.fut`, It throwed an error
![屏幕截图 2023-05-23 142810](https://github.com/diku-dk/futhark/assets/35684738/833c3775-589c-4679-b002-dc29882e9d81)
.
The lib of cuda on windows is not .a file, I think the gcc on windows can't link the .lib file. So should I use vs to replace gcc? 
Isn't Futhark's current support for Windows very good? Do I need to use it under Linux?

**Comment by athas** [comment]
Futhark expects that you have a working C compiler that can compile using standard command line options.  It doesn't know anything about how to set that up (environment variables etc), though.  I know it is possible to get this to work, but I've long since forgotten the details.  I have no idea what the files are called on Windows.  If you can get plain `gcc foo.c -lcuda -lcudart -lnvrtc` to work, then Futhark will work.

I think the majority of people who use Futhark do so through Linux, macOS, or WSL.

**Comment by wujilingfeng** [comment]
I don't seem to have found a solution.
I have used opencl successfully. And I‘m testing multicore, It seems that we need to configure pthread first.

**Comment by wujilingfeng** [comment]
I don't seem to have found a solution.
I have used opencl successfully. And I‘m testing multicore, It seems that we need to configure pthread first.

**Comment by athas** [comment]
The multicore backend does not work on Windows, as it uses pthreads.

**Comment by wujilingfeng** [comment]
Such is the case.No matter how I configure pthread, it doesn't work.
I see. It is recommended to use the opencl backend on the Windows platform. I just want to understand the cross platform nature of Futhark.
Thank you !
