### ISSUE TITLE
Will “if else” statements in programming languages reduce computational efficiency?

### ISSUE THREAD

**Issue by wujilingfeng** [diku-dk/futhark#1973]
Generally speaking, excessive ”if else“ in a GPU can reduce computational speed. Is this the same in futhark, or do you have optimization?

In order to prevent excessive "if else", I usually adopt the following numerical calculation simulation.
```

def ge_zero (a:f32):f32= (f32.sgn a + 1)/2.0

def ge_ifelse (x:f32) (y1:f32) (y2:f32) :f32=let u= ge_zero x in u* y1 +(1-u)*y2  
```
Is it necessary?

**Comment by athas** [comment]
Futhark by design does not micro-optimise scalar code much.  `if` generally turns into branches.  If you think your code will run faster by avoiding branches, then you need to do arithmetic control flow, as in your example.  I will say that on modern GPUs, I don't notice control flow being slow at this level.

**Comment by wujilingfeng** [comment]
> Futhark by design does not micro-optimise scalar code much. `if` generally turns into branches. If you think your code will run faster by avoiding branches, then you need to do arithmetic control flow, as in your example. I will say that on modern GPUs, I don't notice control flow being slow at this level.
I konw, Thank you very much!
I konw, Thank you.
