### ISSUE TITLE
Error parsing declarations with negative sign and no white space

### ISSUE THREAD

**Issue by dominicmkennedy** [diku-dk/futhark#2022]
The Futhark compiler seems to have some odd behavior surrounding declarations with negative sign, and no white space.
Given these three declarations in a Futhark program: 
```
let a = -1
let b =(-1)
let c =-1
```

The compiler has no problem with lines one and two, but on line three gives the following error: `Unexpected token: '1'`.
If line three of the program is changed to `let c =-a`, the compiler will instead give the error: `Unexpected end of file.`.
Both of these are different than the error when line three is executed in the REPL it gives this error instead: `Unexpected token: '=-'`.

**Comment by athas** [comment]
This is not an error, but a result of the tokenisation rules.  We can check this by putting that text in a file and running `futhark tokens` on it, which will yield this (I have inserted empty lines for clarity):

```
LET
ID (Name "a")
EQU
NEGATE
NATLIT (Name "1") 1

LET
ID (Name "b")
EQU
LPAR
NEGATE
NATLIT (Name "1") 1
RPAR

LET
ID (Name "c")
SYMBOL Equ [] (Name "=-")
NATLIT (Name "1") 1
```

Note how for the last line, the minus sign becomes part of the `=-` token.  This is because `-` is a valid symbol character.

The different error message between the compiler and the REPL is likely because the REPL will try to parse the input as both a declaration or an expression, while the compiler will expect only a declaration.  If you change the last line to `def x = let c =-1`, meaning the compiler will also read the mangled `let` as an expression, then the error is the same.

In the REPL, the error is different because the REPL will expect an expression.

**Comment by athas** [comment]
I don't see how this could be changed, as we definitely want both `=` and `-` to be allowed as part of an operator.  It may be possible to add some special cases to the parser to detect cases like this, but I'm not sure what the rule should be.

When you write `let a=-b=1`, you are *defining an operator* with name `=-` whose two parameters are `a` and `b`, and which always returns 1.  It's the same as writing this:

```
def a =- b = 1
```

**Comment by dominicmkennedy** [comment]
> When you write let a=-b=1, you are defining an operator with name =- whose two parameters are a and b, and which always returns 1.

This actually makes a lot more sense now. I don't know why I didn't think about it like that previously.

> It may be possible to add some special cases to the parser to detect cases like this, but I'm not sure what the rule should be.

I may try and look into a special rule, if it seems reasonable to implement. Otherwise I like the rationale behind keeping the behavior the same, thanks for taking the time to explain.
