### ISSUE TITLE
Support ghc 9.8

### ISSUE THREAD

**Issue by chenrui333** [diku-dk/futhark#2045]
👋 while trying to build the latest release, I ran into some build failure against latest ghc 9.8.1

```
  ==> cabal v2-install --jobs=4 --max-backjumps=100000 --install-method=copy --installdir=/opt/homebrew/Cellar/futhark/0.25.8/bin
  Error: cabal: Could not resolve dependencies:
  [__0] trying: futhark-0.25.8 (user goal)
  [__1] trying: versions-6.0.3 (dependency of futhark)
  [__2] next goal: base (dependency of futhark)
  [__2] rejecting: base-4.19.0.0/installed-inplace (conflict: versions =>
  base>=4.10 && <4.19)
  [__2] skipping: base-4.19.0.0 (has the same characteristics that caused the
  previous version to fail: excluded by constraint '>=4.10 && <4.19' from
  'versions')
```

relates to https://github.com/Homebrew/homebrew-core/pull/154041

**Comment by athas** [comment]
Looks like it is the versions package that does not support GHC 9.8. It will certainly catch up soon, and from what I remember it is actually just an overly restrictive bound that is at fault. That can be fixed by asking cabal to ignore upper bounds, but if Homebrew still has GHC 9.6 as well, it is probably easier just to use that version for this release.

**Comment by athas** [comment]
Well, it's not just `versions`, it's also beefier things like `lsp-types`.  I see PRs for the various packages (and made a few myself), but it'll probably take a week or two before Futhark can be compiled with GHC 9.8.  I expect you'll see similar errors for many other Haskell packages in Homebrew.  GHC 9.8 is about a month old, and usually it takes a bit longer than that for all the package maintainers to adjust their code.

**Comment by athas** [comment]
GHC 9.8 is fully supported now.
