### ISSUE TITLE
Justification for Alias Tracking

### ISSUE THREAD

**Issue by andrewthad** [diku-dk/futhark#2118]
I'm not a user of futhark, just a PL enthusiast interested in non-imperative approaches to handling in-place updates. My question is about  a gap in futhark's documentation. Section 3.10.1 explains how alias analysis works very well. Alias analysis is an uncommon feature to include in a type system, and what is left unexplained is why alias analysis exists. That is, what kinds of programs does it let users write that could not be written if the type system performed a more simple "consumption analysis". (Consumption analysis meaning the thing that a language implementer would typically perform for an affine type system.) One example I can think of is something like this:

    let a = ... -- something that returns a freshly allocated array
    let b = a
    consume(a)

But that's a contrived example, and I doubt that it's the reason for alias analysis. I tried to think of an if-then-else example, but both alias tracking and consumption analysis would work the same way for this:

    let y = ... -- fresh array
    let z = ... -- fresh array
    let x = if myCondition then y else z
    let w = consume(x)
    -- cannot use y or z here, either with alias tracking or consumption analysis

Maybe it has something to do with records, where an alias could refer to either a path into a record or to the record itself. I'm not sure though. If you would be able to provide an example that illustrates why this design decision was made, I would appreciate it. And it would be great to include in the documentation.

**Comment by athas** [comment]
First of all: it's certainly possible that we got the aliasing system wrong, and that it is more complicated than it has to be. It has actually gone through several rounds of simplification. Many programs don't need any of the consumption/aliasing features at all, but there are some critical examples of algorithms that we simply don't know how to express in a work-efficient manner without them.

Your contrived example is actually pretty close to the truth. The reason is that many array index space transformations (slicing, reversing, take/drop, etc) produce aliased arrays. Those could be affine (or even linear) operations instead, but we reasoned that this would actually make the language more complicated. One principle that we have tried to adhere to is that if you are a programmer who doesn't use consumption anywhere, you don't need to worry about any of this aliasing business (this is not entirely the case today, but it's fairly close).
