### ISSUE TITLE
Is it possible to add a compiled version of the windows version available for download?

### ISSUE THREAD

**Issue by fenginsc** [diku-dk/futhark#2121]
The latest release and the daily builds don't have windows downloads anymore, and the daily builds had windows versions before, but now they don't either.
https://github.com/diku-dk/futhark/releases/tag/v0.25.14
https://github.com/diku-dk/futhark/releases/tag/nightly

**Comment by athas** [comment]
The Windows builds stopped working at some point (a compilation error in the `bytestring` dependency about a missing header file), and since I don't have a Windows machine available I cannot debug it, so I removed them from CI.  The relevant commit is 65d4f06468ab6865276001db1a37fffb72f458ee. I don't mind someone figuring out what goes wrong, but I am unlikely to do it myself.

**Comment by fenginsc** [comment]
I see that I've upgraded the ghc compiler version, retrying with the latest compiler to see if that fixes the compilation error reporting problem.

**Comment by fenginsc** [comment]
I submitted a PR to fix the compiled CI for the windows version. https://github.com/diku-dk/futhark/pull/2130

**Comment by athas** [comment]
I have merged that PR. Thanks!
