### ISSUE TITLE
FFIing OpenCL code from C/C++ without using stdin/out?

### ISSUE THREAD

**Issue by hermestobias** [diku-dk/futhark#355]
Is it possible to use futhark-opencl to generate C code that I can call from another C/C++ function? My option right now is to manually remove the main function from the generated code and call entry_main() from my other code, using redirected stdin and stdout.

**Comment by Athas** [comment]
Unfortunately, the C backend is still somewhat embryonic when it comes to generating reusable libraries.  The reasons are technical, not conceptual: C has no standard representation for multidimensional arrays, and no good way of doing structured error handling, so writing a robust interoperable library is a little tedious, and I've not been able to justify the time investment so far.  However, I think it's time to start on this work - it should not take more than a week or two for me to get a basic prototype working.  Error handling will probably still be by terminating the process whenever things go wrong, as robustly returning errors without potentially leaking memory will require a bit more thought.

If it's applicable to your use case, you can try the Python/PyOpenCL backend, which *does* have robust library support (via the `--library` flag to `futhark-pyopencl`).  The performance of the generated code is close to that of the C code, since most of the work is still offloaded to the GPU.  We have lots of examples of how to use this, [Diving Beet](https://github.com/Athas/diving-beet) for example.

**Comment by hermestobias** [comment]
Awsome!

My use case is to hook in the futhark generated code in a C++ desktop application which provides a couple of 3D float images as well as some int and float parameters (number of iterations, physical size, etc), and expecting a 3D float image in return.

What about marshalling an [d][w][h]f32 as a pair of (size_t* sizes, float* data), where sizes in this case is an array with 3 items (in d,w,h or h,w,d order, whatever suits you), and data is a packed array (in d-major or h-major, again - what works for you). For cases like [10][w][w]f32 the sizes can still hold 3 items, but the first element has to be 10 and the other two has to be the same. I am perfectly fine with these constraints not being checked by the runtime but put on me as a user to guarantee.

**Comment by hermestobias** [comment]
As for portability (I'd like to build the generated C-code in Visual Studio), I currently have to remove the inline directives on futhark_log32 and friends, and have to move out the OpenCL code-strings into external files (or resources) since VC++ doesn't allow string literals longer than 16K.

**Comment by Athas** [comment]
How come `inline` doesn't work?  We can remove them - most C compilers should be able to figure out that these functions are pretty good inlining candidates.

I'll also split up the large string.  It does not have to be readable anyway.

**Comment by hermestobias** [comment]
inline is C99, which Visual Studio doesn't support. 

If you split up the string, please note that even the compile-time concatenated result ("concatenate " "these " "strings") has to be under 16K.

**Comment by hermestobias** [comment]
Furthermore (after hacking in my own marshalling into the entry):
*  VS doesnt have getopt, so I had to make my own like this https://stackoverflow.com/questions/10404448/getopt-h-compiling-linux-c-code-in-windows
* snprintf had to be replaced with _snprintf, see https://stackoverflow.com/questions/3976306/using-snprintf-in-a-cross-platform-application

**Comment by hermestobias** [comment]
Unfortunately, it seems that Futhark doesn't quite scale with our application. 

When running the simplest version of our algorithm on an albeit pretty large dataset (input is 56MB, and result and working set is 120MB), futhark dies with OpenCL error code -5 (out of resources). In the debugger I can see that it tries to allocate num_threads times my working set size of 120MB, which with 256 threads ends up at 32GB!

I guess with our use cases we need to retain control over memory usage and can't really go with a high level language like futhark, which is too bad. I still think OpenCL and CUDA is a too low level of abstraction though...

**Comment by Athas** [comment]
What's likely happening is that the Futhark compiler isn't certain how much parallelism is needed.  We currently use heuristics to decide that to sequentialise and what to parallelise, and sometimes those heuristics are wrong.  We are working on a multi-versioned approach, where different parallel structures are generated, and the more parallel ones (which also require much more memory) are only used when necessary.

I would like to see your program, though.  Sometimes there is a simple way to prevent the compiler from doing something that stupid (and maybe the bug is something else in this case).

**Comment by hermestobias** [comment]
Have emailed you
