### ISSUE TITLE
Add hexadecimal float literals

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#382]
Read the justification for a similar proposal for GHC: https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0004-hexFloats.rst

This should be doable as a mere lexer change.

**Comment by samrat** [comment]
My WIP commit for this issue: https://github.com/samrat/futhark/commit/dfd5e9e206124b589dbe10aaaffcb3d8f14256e5. Comments welcome, since I'm quite new to Haskell.

Questions: 
- Will this syntax be supported: `0xff.ffp2f32` ? My current commit will always create a `f64`. There is a tradeoff here: if we support specifying `f32`, the exponent will always have to be present(in order to disambiguate the "f"-- see https://gcc.gnu.org/onlinedocs/gcc/Hex-Floats.html)
- Will hexadecimal floats also be supported as input? ie. will the Python & C readers also need to support hexadecimal floats?

**Comment by Athas** [comment]
I think we should definitely support the numeric suffixes.  If that requires that the exponent is required, so be it.

I would definitely prefer that the Python and C readers are also extended, but it is not critical.  It can be made a separate issue if you'd rather not spend your time on that.
