### ISSUE TITLE
zip assert

### ISSUE THREAD

**Issue by melsman** [diku-dk/futhark#397]
The following program should fail at runtime, but it doesn't:

````
let predict (a:[10]f64) : i32 =
  let (m,i) = reduce (\(a,i) (b,j) -> if a > b then (a,i) else (b,j))
                       (a[9],9)
                       (zip (a[:8]) (iota 9))
  in i

let main() : i32 =
  predict [0.2,0.3,0.1,0.5,0.6,0.2,0.3,0.1,0.7,0.1]
````

The [documentation for `zip`](https://futhark.readthedocs.io/en/latest/language-reference.html#expressions) states

> Static or runtime check is performed to check that the sizes of the outermost dimension of the 
> arrays are the same. If this property is not true, program execution stops with an error.

Here is a better implementation of the program, which fixes `a[:8]` to read `a[:9]` and which, correctly, will result in the prediction `8i32`:

````
let predict (a:[10]f64) : i32 =
  let (m,i) = reduce (\(a,i) (b,j) -> if a > b then (a,i) else (b,j))
                       (a[9],9)
                       (zip (a[:9]) (iota 9))
  in i

let main() : i32 =
  predict [0.2,0.3,0.1,0.5,0.6,0.2,0.3,0.1,0.7,0.1]
````

A fix is not urgent....

**Comment by Athas** [comment]
This is an instance of the fact that the Futhark compiler does not maintain assertions for code that is simplified away, or removed due to dead code elimination. This is probably what we want. In this particular case, the iota is inlined. We could probably maintain the check somehow by relating it to the remaining expressions, but doing so for general dead code elimination would likely be very involved. It may be a better idea to come up with some precise description that checks may be removed by the compiler if they do not cause the program to behave unsafely. Errors are not

**Comment by Athas** [comment]
I have come to the conclusion that it is time for fix this for good.  Or rather, introduce the general mechanism by which we can solve all the myriad special cases where this issue shows up.  The general idea is to permit *any* statement to contain a `Certificates` list; thus creating "artificial" data dependencies.  We will have to fix each simplification rule on a case-by-case basis, unfortunately.
