### ISSUE TITLE
A semantics for empty arrays

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#398]
We currently have some underspecification related to empty arrays in Futhark.  Specifically, what the size of their dimensions should be.  The problem is rooted in our size analysis, which tries to infer the correct size of inner dimensions, even when outer dimensions may be zero.  This size analysis is extremely important to supporting fusion and other optimisations, so we should not get rid of it.  As an example, consider the following expression fragment:

```
let yss = map (\x -> f x) xs
```

Here we are mapping some one-dimensional array `xs` with the function `f`, which also returns an array, such that the result of the `map` in its entirety is a two-dimensional array `yss`.  Suppose `xs` has shape `[n]`.  What, then, is the shape of `yss`?  We must know this before we can evaluate the `map`.  With our current size analysis, we apply `f` to the first element of `xs` to determine the size ahead of time, protected by a branch to guard against the case where `xs` is empty:

```
let m = if n == 0 then 0 else length (f xs[0])
let yss = map (\x -> f x) xs
```

So far, so good.  However, in some cases we may have more information.  Perhaps `f` has a size annotation on its return type, such that we can predict the size without reading `xs[0]`.  Perhaps the size of the value returned by `f` does not depend on the value of `xs[0]` at all, and so later inlining/simplification will remove the branch (this is a very common case).  In such cases, even when `xs` is an empty array, we can infer a non-zero size for the inner dimension of `yss`.   For example, consider this fragment:

```
let yss = map (\x -> [x,x]) xs
```

If `xs` is empty, should the shape of `yss` be `[0][0]` or `[0][2]`?  Ff the program explicitly refers to the size of the innermost dimension of `yss` (by using `shape` or size parameters), the program result may then be changed by optimisations performed by the compiler, which is clearly not desirable.  Not only is it fragile to small changes in the program, but it also makes it hard to write a non-optimising reference interpreter for Futhark that produces the same results as the compiler.  This is not a good situation.

Since the size simplifications performed by the compiler are very important enabling optimisations, simply not doing them is not an option.  Instead I propose changing the semantics of `shape` (and size parameters) such that the behaviour is consistent no matter which simplifications are performed.  This will lose us some algebraic equalities, however.

Specifically, I propose that when the shape of an array is being referenced by user code, *any dimension following a zero dimension will likewise be zero*.  The only places where user code can refer to array sizes is by the return value of `shape` and by referencing size parameters, and it is easy to simply multiply the dimension referenced by the sign of outer dimensions.  I do not think this should have much impact on the compiler.

We lose some algebraic equalities with this approach.  For example, currently we have that `shape (reshape s x) == s`.  This will be lost, as my proposed change would bring `shape (reshape (0,2) xs) == (0,0)`.  I am not sure how valuable these algebraic equalities are, so I'm not too worried.  However, I'm open to other solutions to the problem (requiring full size annotations from the user is not a solution).

**Comment by Athas** [comment]
As an experiment, I tried disabling the optimisations in question, and it resulted in lots of problems even on small programs.  I guess we cannot avoid addressing this issue.

**Comment by henglein** [comment]
What is the semantic basis of this proposal?  What does the literature say?

Zero and zero-dimensional structures play a critical role as neutral and
absorbing elements.  In either case, they point to algebraic equalities:
two values giving rise to identical or isomorphic structures.

Consider Gains and Mullin's algebra of multidimensional arrays; it has
equalities
[n, 0] T = [0] T = [0, n] T = O (the empty array at any rank),  [n, 1] T =
[n] T and [1] T = T, which together yield that there are only the empty
array O and arrays of types [n1, ..., nk] T where, ni > 1.   Treating the
above isomorphisms (see below) as equalities entails that an interpreter or
compiler must insert the isomorphisms implicitly in any context an array is
used. This is tricky: It essentially boils down to treating all arrays as
one-dimensional with a (normalized, only >1 dimensional at each rank) shape
sequence as in APL; see e.g. Def. 14 of indexed array access.  This does
not reflect the intuition of an array having a fixed rank, independent of
its dimension at any rank, which might be set at run time: "construct an
array of size [= dimension] n, where n is read from the input".

Consider then the above equalities as isomorphisms: The programmer (or
maybe the compiler) can write/infer them, but they are not equal.  Another
semantic interpretation is natural to let [n] denote {0, ..., n-1} ("iota
n") and [n] T as the type of maps from [n] to T; where [n, m] is an
abbreviation of [n] x [m], the Cartesian product of [n] and [m].
Then the first equalities above, [n, 0] T = [0] T = [0, n] T = O hold, but
not the ones with 1 -- they are isomorphisms (element ~ array with one
element).  If T has a bit of structure, e.g. it is a group then [n] T
corresponds to standard (free) structure constructions: If K is a field, it
is K^n, the vector space of n-tuples; [n, m] K = ([n] x [m]) K represents
the tensor product of [n] T and [m] T; and [n] [m] K represents the linear
maps from [n] K to [m] K, the
the (m x n) matrices over K; matrix in the sense of matrix algebra, with
associated operations such as matrix multiplication, rather than being just
tables (rectangles) of K-elements by themselves.  (The O is the unique
element, the zero, of the zero-dimensional vector space then.)

What does this have to do with the question about [0][2] versus [0][0]?
The first answer is: In the above model these are not well-formed: [0][2]T
and [0][0]T are well-formed.  They both denote O; conversely, O has all
those shapes, not just one particular one.  How to implement that?  I don't
know, maybe by normalizing the shape to [0][0]T so long as it does not ruin
the semantic model.

Keeping the (denotational) semantics in mind is practically useful:  It
keeps the focus on what is models and which properties it has, rather than
letting implementation considerations drive the design process since there
is a way of checking whether tricks of implementation are sound and
complete wrt. the semantic model; without it, any trick of implementation
suddenly becomes the semantics, algebraic properties might be lost with
unintuitive behavior down the line, with more tricks required to address
those, etc.

Fritz

**Comment by Athas** [comment]
The semantic basis of Futhark is probably more the lambda calculus than traditional array programming literature.  As you mention, tn the usual array tradition, arrays are seen as a flat vector of values augmented by a shape vector.  In Futhark, an array is more of a recursive structure, where it makes sense to operate on the intermediate levels (this is painful in e.g. APL).  This is why we have problems that they don't have, and why the literature does not have a conclusive answer.

Permitting the equality `[n, 0] T = [0, n] T` has some practical issues for termination.  For example, consider the program

```
let x = replicate 0 (replicate n 42)
let y = map (\_ -> 0/0) x
```

This program terminates successfully, because zero iterations of the `map` are executed, and thus the division by zero is never encountered.  However, the following program will fail (assuming `n != 0`):

```
let x = replicate n (replicate 0 42)
let y = map (\_ -> 0/0) x
```

In a conventional array calculus these two programs would be identical, because the `map` would always operate at the "bottom" level.  In Futhark, only the outermost dimension is "stripped off".  In essence, Futhark's arrays are inductive data types, which is a bit unusual for an array language.

However, you are right that we need to think about a calculus-based justification, even if that calculus is not fully expressed in the language.  I was distraught that we might lose the equality

```
shape (reshape s x) == s
```

*However*, while Futhark models a shape as a mere vector of integers, most array calculi I have seen maintain an entirely separate notion of a "shape object", which can impose their own rules for equality (which may be more like isomorphisms).  So, in Futhark, the equality should be

```
shape (reshape s x) =~= s
```

where `=~=` is some shape-equality operator that disregards everything after the first zero.

**Comment by athas** [comment]
Subsumed by #823 which fixes everything related to this.
