### ISSUE TITLE
array length: parse error

### ISSUE THREAD

**Issue by alexpanter** [diku-dk/futhark#402]
The following code snippet simply reports a "Parse error at <file.fut>:X:Y-Z:W".
It could be stated instead, that the input array length argument is not recognized as an int, or something similar.

```
type int = i32
let main(xs: [int]) : []bool =
  [true]
```

-alexpanter

**Comment by Athas** [comment]
That is a parse error.  Use `[]int`, not `[int]` (but why the `int` alias anyway?).

**Comment by alexpanter** [comment]
I know that it is invalid, but I think the error message could be improved upon. As for the int alias, no it is not necessary, just found it in an example

**Comment by Athas** [comment]
The problem is not just that array length argument is bad (it's not - there might be a variable `int` in scope, which the parser cannot know), but that there is no base type for the array.  But sure, it would be nice to report better parse errors, in this and other cases, but I'm not sure whether the parser generator we use ([Happy](https://www.haskell.org/happy/)) is up to the task.  GHC also uses Happy, and it has completely dismal parse error messages.

**Comment by Athas** [comment]
Turned out that this case (and a few others) can be detected by adding a few new productions to the grammar, which then emit a custom error message.  The parse error should be better now.
