### ISSUE TITLE
Invalid work group size 

### ISSUE THREAD

**Issue by luxint** [diku-dk/futhark#447]
When trying to run the test programs:  futhark-test tests --compiler=futhark-opencl I get below error messages (I've included the last two but the rest are similar, global_work_sizze_nnnn is 4 'smaller' then local_work_sizze_nnnn)

Have installed  futhark on MacBook pro (Intel HD Graphics 530 & AMD Radeon Pro 455) OS: 10.12.6 (Sierra). 

(Programs compiled with futhark-c , run without any problems.)

Running compiled program:
Running ./tests/uniqueness/uniqueness7 -e main:
validating test result:
Program failed with error code 255 and stderr:
  ./tests/uniqueness/uniqueness7: tests/uniqueness/uniqueness7.c:3074: OpenCL call
  clEnqueueNDRangeKernel(ctx->opencl.queue, ctx->kernel_iota_2892, 1, NULL, global_work_sizze_2903, local_work_sizze_2907, 0, NULL, NULL)
failed with error code -54 (Invalid work group size)

tests/uniqueness/uniqueness16.fut:
Entry point: main; dataset: #0 ("1i32"):
Running compiled program:
Running ./tests/uniqueness/uniqueness16 -e main:
validating test result:
Program failed with error code 255 and stderr:
  ./tests/uniqueness/uniqueness16: tests/uniqueness/uniqueness16.c:3354: OpenCL call
  clEnqueueNDRangeKernel(ctx->opencl.queue, ctx->kernel_replicate_4281, 1, NULL, global_work_sizze_4379, local_work_sizze_4383, 0, NULL, NULL)
failed with error code -54 (Invalid work group size)

294 failed, 496 passed (1 excluded).

**Comment by Athas** [comment]
Yeah, this is an issue that keeps cropping up.  The issue is that macOS has several OpenCL "platforms" (backends) available.  At least a CPU backend, and then possibly one or more GPU backends.  The CPU platform is first in the list, so it is the one Futhark picks by default.  For some reason, the CPU backend seems to misreport its maximum workgroup size, so Futhark's attempt to automatically calibrate the workgroup size fails the way you observe.  I have not yet been able to gain access to a macOS system so I can debug exactly what is going on, but I plan on changing that within a few months.

The workaround is to specifically ask for a different OpenCL platform.  I don't know exactly what they are called on your system (maybe you can use [`clinfo`](https://github.com/Oblomov/clinfo) to find out), but once you do, you can pass the `-p` option to a generated Futhark executable to pick another platform.  For example:

```
./foo -p'AMD'
```

would use the first platform that contains the string "AMD" anywhere in its name.  It is also possible to use a platform by position.  Thus,

```
./foo -p'#0'
```

uses the first platform (the default), and

```
./foo -p'#1'
```

would use the second.

When using `futhark-test`, you can use `--pass-option` to pass an option along to the generated executables, like this:

```
futhark-test --compiler=futhark-opencl --pass-option='-p#1' --exclude no_opencl
```

(You want `--exclude no_opencl`, because some programs in the test suite cannot yet be handed by the OpenCL backend.)

We should probably make a FAQ where this is the first question.

**Comment by luxint** [comment]
Thanks for your quick reply but it didn't work ;-) I got an "Could not find acceptable OpenCL device"  if I tried --pass-option='p#1'  or 'pAMD' ...

But  after some googling around  what did work was: futhark-test  tests --compiler=futhark-opencl --pass-option='-dAMD' --exclude no_opencl

**Comment by Athas** [comment]
Good that you found a solution!
