### ISSUE TITLE
Negative allocations due to hoisting out of loops

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#479]
This somewhat contrived program attempts to perform an allocation of a negative amount of memory for some inputs:

```
let main (n: i32) =
  loop x = replicate 2 0 for i < n-100 do
    (map (+i) (iota (n-100)))[::-1]
```

One solution would be to hack allocations to they they ignore negative allocation attempts, but that might obscure legitimate bugs.  The real solution is to protect allocations that we hoist out of loops.  I suspect a similar issue exists for branches.

**Comment by Athas** [comment]
Ah, we never hoist allocations out of branches (except if they are inside kernels), so that should not happen.

**Comment by Athas** [comment]
The root of the issue is that we have previously depended on aggressive allocation hoisting, and facilitated this by marking `alloc` statements as "cheap" (which is harmless), as well as "safe" (which is not), and then adding various hacks to avoid the unsafety.

The solution is to mark allocations as unsafe, which they certainly are in absence of other information, and then adding various rules to modify and hoist them anyway, when possible.  Safety first.
