### ISSUE TITLE
map example doesn't compile

### ISSUE THREAD

**Issue by headsvk** [diku-dk/futhark#546]
The function `combineChannels` in [Gaussian Blur Stencil example](https://futhark-lang.org/examples.html) fails to compile with futhark-c 0.4.1 and 0.5.0, throwing this error:

`Type error at example.fut:6:14-9:37:
Type used at example.fut:6:10-6:10 must not be functional, but is f32 -> f32 -> *[]u8.
When matching type 'a5 -> x6' with 'f32 -> f32 -> f32 -> *[]u8'.`

How is the map supposed to be used now?

**Comment by Athas** [comment]
Sorry, looks like I forgot to push the website changes when we changed the `map` construct.  It should work now.  The short answer is that we made `map` into a proper function instead of magic syntax, so now one has to use a `map3` function to map across three arrays simultaneously.  There is also the [full blur.fut source file](https://futhark-lang.org/static/blur.fut).
