### ISSUE TITLE
Abort trap: 6 with integrated Intel GPU on OS X

### ISSUE THREAD

**Issue by zeebo** [diku-dk/futhark#571]
I'm running a program that works on other machines (a MBP with an AMD graphics card, for example) and with the `futhark-c` compiler, but it fails when running with any opencl backend. It seems like sometimes it will complete when I only run it once (no `-r 2`), but I get a beachball, log entries about GPU crashes and it takes >7seconds to complete, which is far too long.

Here is all of the relevant information I could gather from my machine: https://gist.github.com/zeebo/63256978cb8c5787c896c1f5b09e6338

Please let me know if there's anything more I can do to debug this.

**Comment by Athas** [comment]
I'm always inclined to blame GPU driver bugs for things like this (just yesterday I found a bug where the AMD kernel compiler would miscompile nested while loops sometimes).  However, the Futhark compiler does actually generate some slightly odd code for the reduction here; specifically the reduction *before* the one that crashes contains some barrier divergence because the loop tiler is too aggressive (that might explain why it takes so long to run).  I can't possibly imagine why that would manifest as a bug in a subsequent kernel invocation, but you can try disabling tiling entirely and see if that makes a difference.  Download Futhark from source and edit the file [src/Futhark/Passes.hs](https://github.com/diku-dk/futhark/blob/master/src/Futhark/Passes.hs) by commenting out the line

```
         , tileLoops
```

to

```
--         , tileLoops
```

thereby disabling the loop tiling pass.  Install with `stack install` by the [compilation instructions](http://futhark.readthedocs.io/en/latest/installation.html#compiling-from-source) and see if it helps.

**Comment by Athas** [comment]
I can reproduce this on my own Mac, and tiling indeed seems to be the culprit.

**Comment by Athas** [comment]
I have committed what I believe is a fix.  Can you check whether it solves the problem for you?

**Comment by zeebo** [comment]
The current master (7c70db10501c7cf55df5aa6e8414099d28ac4910) has indeed fixed the problem for me. Thanks!
