### ISSUE TITLE
Thread safety of futhark-opencl generated code

### ISSUE THREAD

**Issue by vsenko** [diku-dk/futhark#585]
I'm experimenting with Futhark and currently got an issue with calling **futhark-opencl** generated code from different threads.

I'm calling `futhark_context_config_new()` and `futhark_context_new()` from the main thread, then spawn several worker threads. Each one calls:
- some data initialization functions (like `futhark_new_f32_1d` or `futhark_new_f32_2d`)
- then it calls the entry point function
- after that it tries to obtain the results (like `futhark_values_f32_1d` or `futhark_values_f32_2d`)
- and finally it cleans up (`futhark_free_f32_1d` or `futhark_free_f32_2d`)
- does it in a loop

Whenever I launch more than one worker, I get ugly crashes. Are there any guidelines or limitations for code generated by **futhark-opencl**?

My environment:
Ubuntu 18.04
nvidia GeForce GTX 1060 GPU
OpenCL library from default nvidia drivers
If there is anything else I can provide, please guide me.

By the way, code generated by **futhark-c** works well with several parallel worker threads.

**Comment by Athas** [comment]
A single `futhark_context` should not be used by more than one CPU thread at a time.  It may work when using `futhark-c` because the context contains very little, but I'm not surprised at explosive results when using `futhark-opencl`.   The underlying OpenCL API is thread safe (as far as I can determine), so this could theoretically be supported at the Futhark level as well, although I worry it may inhibit our ability to do more sophisticated scheduling in the future.

Is this very important to you, or could you get away with proxying all Futhark calls through a single worker thread (or just maintain your own mutex around the calls to Futhark functions)?

One easy solution for Futhark would be to just keep a mutex in the context and force single-threaded access internally.  The only problem here is that Windows does not support the pthreads API, so I don't know what it would look like there.

**Comment by vsenko** [comment]
Thank you for your response! Now I see that it's not safe to do such reckless things.

Is it safe and reasonable to have several threads with different `futhark_context_config`s and  `futhark_context`s? This way I could launch some worker threads and distribute workload between them.

**Comment by Athas** [comment]
Yes, that would be safe, but it would not be safe to pass values returned by one entry point to another.  You'd first have to use `futhark_values` to produce a CPU-side array, and then construct a new array using the desired target context.

I would not be opposed to trying to make the Futhark API thread-safe if you this is an important use case, but I'm always [reluctant to add more moving parts](https://futhark-lang.org/blog/2018-06-18-designing-a-programming-language-for-the-desert.html), so if you can solve your problem with workarounds for now, I can just note in the documentation that the API is not thread-safe.

**Comment by Athas** [comment]
Actually, if I can figure out how to get it to work on Windows, I will definitely just make the Futhark API thread safe (in a naive way by internal locking).  It is contrary to our philosophy to leave such a booby trap around.

**Comment by vsenko** [comment]
> Yes, that would be safe, but it would not be safe to pass values returned by one entry point to another. 

Excellent, I'll try this approach! Thank you for support!

**Comment by vsenko** [comment]
As for me, I think it is quite enough to mention in the docs that API is not thread safe and to suggest a workaround (like having a pool of workers).

Naive internal locking is a good safety feature but absence of explanation of locking in the docs would lead to naive attempts to use context from multiple threads which in turn would lead to degraded performance and unfulfilled expectations.

Thank you again!
Should I close this one?

**Comment by Athas** [comment]
I updated the documentation and created #586 to track the introduction of thread safety.
