### ISSUE TITLE
Distribute via Hackage

### ISSUE THREAD

**Issue by srhb** [diku-dk/futhark#614]
Currently, futhark is not on Hackage, which means that nixpkgs does not automatically get the package when our hackage packageset is regenerated -- see https://github.com/NixOS/nixpkgs/pull/43865

It would be very nice if it were hackage'd. :-)

**Comment by athas** [comment]
I don't mind doing this, but Futhark does not (and will not) follow [the PVP](https://pvp.haskell.org/faq/), but rather [SemVer](https://semver.org/), because that is more common outside the Haskell community, and Futhark is only incidentally implemented in Haskell.

I don't really care that much - there are plenty of non-PVP packages on Hackage - but it's also a fight I'm reluctant to spend too much time on.

**Comment by srhb** [comment]
Understandable. It's not too onerous for us to package futhark without the benefits of automatic Hackage  updates, but a bit of a shame nonetheless.

**Comment by athas** [comment]
Futhark 0.7.3 is [now on Hackage](http://hackage.haskell.org/package/futhark-0.7.3).  I'm not sure how useful it is in its current state, and it's currently a manual process to upload new versions, but this should be a good starting point.
