### ISSUE TITLE
Clarifying how to pass data to a compiled executable

### ISSUE THREAD

**Issue by zmitchell** [diku-dk/futhark#639]
Hi, I'm playing around with futhark, but I'm not confident that I know how best to pass data to a compiled, standalone executable.

For example, let's say I just want to add two arrays, then add up the values in the resulting array. Here is the program I've written for that.
```
-- my_program.fut
let main [n] (xs: [n]f64) (ys: [n]f64) : f64 = reduce (+) 0 (map2 (+) xs ys)
```
I compile it with `futhark-c`:
```
$ futhark-c my_program.fut
```
It's my understanding that I need to pass data in over stdin, so I do this
```
$ echo "[1,2,3]" "[4,5,6]" | ./my_program
21.000000f64
```
and it works as expected.

A practical concern is what to do when I have data that's in files. I see there's a binary format I can use, but for now let's say I'm dealing with text data of the form
```
[1.0,2.0,...]
```
I want to do the same operation as before, but loading the data from the files. Here's how I do it:
```
$ echo $(cat test_data_00.txt) $(cat test_data_01.txt) | ./test_futhark
```

This is really slow for files that are large. Is there a better way of doing this short of using the binary format?

**Comment by athas** [comment]
If your files are large, then it's likely that the bottleneck is the parser in `test_futhark` itself.

There is no reason to use `echo` in this case, since `cat` is exactly for catenating files:

```
$ cat test_data_00.txt test_data_01.txt | ./test_futhark
```

...but I would be surprised if shell interpolation overhead is the reason you're dissatisfied with the performance.

Note that it's pretty easy to use `futhark-dataset` to convert textual data to binary data:

```
cat test_data_00.txt test_data_01.txt | futhark-dataset -b > test_data.bin
```

(Or you can do each file separately.)  Doing the conversion with `futhark-dataset` is not particularly fast, but it is a one-time cost, and it makes the parsing by the compiled Futhark program run at disk speed.

If your program also *produces* a giant array, then you can similarly pass it `-b` to produce the result in the binary format, which is orders of magnitude faster than passing it through the textual printer.
