### ISSUE TITLE
Functional programming guidance

### ISSUE THREAD

**Issue by zmitchell** [diku-dk/futhark#641]
I'm learning futhark to see if it's viable for some workflows in my lab, but I'm still getting over the functional-programming learning curve. As a toy problem I want to average all of the columns of an array. Here is the program I wrote to do it (excuse my poor functional programming skills):

```
let cond_split (len: i32) (xs: []f32) : ([]f32, []f32) =
    if (length xs) < len then (replicate len 0.0, []:[]f32) else split len xs

let average_row [n] [m] (arr: *[n]f32) (xs: [m]f32) (ys: []f32) (ind: i32) : (*[n]f32, [m]f32, []f32) =
    let row_avg = (reduce (+) 0 xs) / (f32.i32 m)
    let (new_row, new_remaining) = cond_split m ys
    in (arr with [ind] <- row_avg, new_row, new_remaining)

let main [n][m] (xs: [n][m]f32) : [n]f32 =
    let acc: *[n]f32 = replicate n 0.0
    let flattened = flatten xs
    let (start_row, start_remaining) = split m flattened
    let (averaged, _, _) = loop (arr:*[n]f32, row:[m]f32, remaining:[]f32) = (acc, start_row, start_remaining) for i < n do average_row arr row remaining i
    in averaged
```

This works fine when I do a small array:
```
$ echo "[[1.0f32, 2.0f32, 3.0f32], [4.0f32, 5.0f32, 6.0f32]]" | ./my_prog
```
but hangs on larger arrays i.e. 250000x10. What is the idiomatic way to write this program?

**Comment by athas** [comment]
I assume you mean to average the *rows* of the array (Futhark arrays are notionally row-major, although the actual run-time representation is left to the compiler):

```
let average [m] (xs: [m]f32) =
  f32.sum xs / r32 m

let main [n][m] (xss: [n][m]f32) : [n]f32 =
  map average xss
```

The key here is the use of `map`, which applies a function to every element of an array.  For a two-dimensional array, it applies the function to each row.  `map` is probably the single most common parallel operation.  The `loop` construct is a sequential loop, which you generally want to avoid using unless sequential execution is necessary.

If you really do want to average the *columns*, just transpose the array first:


```
let average [n] (xs: [n]f32) =
  f32.sum xs / r32 n

let main [n][m] (xss: [n][m]f32) : [m]f32 =
  map average (transpose xss)
```

(The name of the dimension in `average` is picked for clarity but need not match the one in `main`.)

**Comment by zmitchell** [comment]
Ah, I didn't realize `map` operated on rows for a 2d array. That makes things much simpler, thanks!

**Comment by athas** [comment]
Beware, however, that you are dangerously close to a research problem!  The issue is that the program has two levels of parallelism (the `map` which contains a `reduce`), and there is no one always-optimal way to parallelise that.  With your original formulation, the Futhark compiler will generate code that exploits both levels, but let's  rewrite the program just a little to take the average of absolutes:

```
let average [m] (xs: [m]f32) =
  f32.sum (map f32.abs xs) / r32 m

let main [n][m] (xss: [n][m]f32) : [n]f32 =
  map average xss
```

Now the compiler will still parallelise the `map`, but the `reduce` will be turned into a sequential loop.  This is a good choice if `n` is large, but for small `n` it may be necessary to also parallelise the `reduce`.  Determining optimal parallelisation is a hard problem, and the compiler by default applies heuristics that usually work OK, but sometimes do not (which is why it's sensitive to such a small change).

If you run into this issue, you can set the environment variable `FUTHARK_INCREMENTAL_FLATTENING=1`, which will enable a new experimental way of parallelising that generates *multiple* versions of the program and picks whichever is best based on the concrete input sizes encountered at runtime.  But it's still experimental, so it might also blow up the compiler.

**Comment by zmitchell** [comment]
Thanks for your help!
