### ISSUE TITLE
Loop unrolling?

### ISSUE THREAD

**Issue by Athas** [diku-dk/futhark#69]
[easter3000.apl](https://github.com/henrikurms/tail2futhark/blob/master/tests/benchmarks/easter3000.apl), after compiling to Futhark with `tail2futhark`, contains a loop with a known number of iterations: 3.  Unrolling this loop would not just avoid the loop itself, but also permit an intermediate array to be simplified away entirely.  It is of course possible that the C compiler can do this optimisation, but I wouldn't bet on it.

When is it permissible to unroll loops?  Should we bother at all?  Perhaps a conservative loop unrolling rule could give us some benefits, whilst still being cautious enough never to cause problems.

**Comment by Athas** [comment]
I should note that the loop in question also has a trivial body - it just sums up an array.  The simplicity of the body could also be used as a yardstick - no unrolling of loops with nested loops, for example.

**Comment by coancea** [comment]
>>When is it permissible to unroll loops?
whenever you know the size statically -- tradeoffs between
code expansion and getting rid of some instructions.
But if entire arrays dissapear it might be worth it.
(However you need to concentrate on fission -- I have distracted you
enough with my bugs :-) )

Come to think of it one application would definitely be
getting rid of size-1 loops (and replacing arrays of statically
known size 1 with scalars.)

B.t.w. I did some work on fixing the current stream.
Now OptionPricing validates again (albeit the big dataset
reaches 27% memory -- but that may be because I do
not fuse inside a user-defined stream yet -- will continue
tomorrow with streams.

However, we need to fix the unnecessary input/result copying
for SOAC -- it looks like it is possible for the common case
but requires symbol tables and a pass similar to copy-propagation
(just the math gets a bit complicated.) -- we'll discuss more when I see 
you.

Best,
Cosmin
