### ISSUE TITLE
Equality and type checking - individual values of array

### ISSUE THREAD

**Issue by TheBlackKoala** [diku-dk/futhark#692]
It seems to me that it is an error that this function does not type-check as you are comparing things of type a with things of type a. I even tried giving v in the lambda-function the type a (\(v : a) ->) and it still does not type-check.

let f 'a (b : a) (bs : []a) = map (\v -> v==b) bs

Error at [0]> :1:45-1:45:
Type a does not support equality.
When matching type
  t2
with
  a

**Comment by athas** [comment]
This is not a compiler error, although the type error is phrased in an unfortunate way.  The problem is that the default built-in equality operator `==` is only defined for built-in primitive types and their composition in arrays and tuples (and I believe this is documented).  Here, you are comparing values of a completely unknown type (`a`), with no intrinsic notion of equality.  If you want to compare these, you must provide your own comparison function:

    let f 'a (eq: a -> a -> bool) (b : a) (bs : []a) = map (\v -> v `eq` b) bs
