### ISSUE TITLE
Array-like types

### ISSUE THREAD

**Issue by TheBlackKoala** [diku-dk/futhark#698]
[0]> type matrix [x][y] = {Inds : [](i32,i32), Vals : []i32}
[1]> let f [n][m] (mat : matrix[n][m]) = (n,m)
[2]> let a = {Inds = [], Vals = []} : matrix[3][3]
[3]> f a
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
`n` is not bound to a value.
CallStack (from HasCallStack):
  error, called at src/Language/Futhark/Interpreter.hs:449:10 in futhark-0.7.0-84nmsNTPywbLlvLS6eNgXN:Language.Futhark.Interpreter

I am trying to make a sparse-matirx library with the dimensions in the type-definition as to avoid illegal function calls.

**Comment by athas** [comment]
I don't think you can do that, and I'm not sure it should even be allowed by the type checker.  It's not clear what the `x` and `y` sizes should have as their concrete values.  You would not be allowed to write that if you inlined the type abbreviation, since all size parameters must be used at least once.

As a workaround, try this type definition:

```
type matrix [x][y] = {Inds : , Vals : []i32, dummy_x : [x]u8, dummy_y: [y]u8}
```

This will allow you to carry around those sizes, and hopefully the compiler will actually not create those arrays.

**Comment by TheBlackKoala** [comment]
First result got:
[1]> type matrix [x][y] = {Inds : [](i32,i32), Vals : []i32, dummy_x : [x]u8, dummy_y: [y]u8}
[3]> let a = {Inds = [], Vals = []} : matrix[3][3]
Error at [3]> :1:9-1:45:
Couldn't match expected type `{Inds: [](i32, i32), Vals: []i32, dummy_x: []u8, dummy_y: []u8}' with actual type `{Inds: *[]t0, Vals: *[]t1}'.
When matching type
  {Inds: [](i32, i32), Vals: []i32, dummy_x: []u8, dummy_y: []u8}
with
  {Inds: *[]t0, Vals: *[]t1}

I tried a second way:
[0]> type matrix [x][y] = {Inds : [](i32,i32), Vals : []i32, x : i32, y: i32}
[1]> let f [n][m] (mat : matrix[n][m]) = (n,m)
[2]> let a = {Inds = [], Vals = []} : matrix[3][3]
Error at [2]> :1:9-1:45:
Couldn't match expected type `{Inds: [](i32, i32), Vals: []i32, x: i32, y: i32}' with actual type `{Inds: *[]t0, Vals: *[]t1}'.
When matching type
  {Inds: [](i32, i32), Vals: []i32, x: i32, y: i32}
with
  {Inds: *[]t0, Vals: *[]t1}

[3]> let a = {Inds = [], Vals = [], x=3,y=3} : matrix
Error at [3]> :1:43-1:48:
Type constructor matrix used without any arguments.
[4]> let a = {Inds = [], Vals = [], x=3,y=3} : matrix[3][3]
[5]> f a
Same error as before

**Comment by athas** [comment]
You have to provide arrays of size `x` and `y` when you construct those values:

```
let a = {Inds = [], Vals = [], dummy_x = replicate 3 0, dummy_y = replicate 3 0} : matrix[3][3]
```

You can of course hide that in a wrapper function.  It is awkward, because what you are trying to do here is not really supposed to work - types are not intended to carry information, so you need to create some value to function as a proxy.

**Comment by athas** [comment]
The original type abbreviation is now correctly identified as a type error by the compiler.
