### ISSUE TITLE
Known compiler limitation encountered.  Sorry.

### ISSUE THREAD

**Issue by sigismundearbuthnotte** [diku-dk/futhark#730]
Compiling to opencl,  I get:
Known compiler limitation encountered.  Sorry.
Revise your program or try a different Futhark compiler.
Cannot deal with existential memory block res_mem_42410 when expanding inside kernels.

This occurs in: Running pass expand allocations.
It happens both in v9 and the Nightly.

Unfortunately, I cannot relate the generated code (it's not C - is it an IL?) to my code in order to revise it - not that I would want to anyway.

Can you advise?

Thanks.

**Comment by athas** [comment]
This is the deadliest error and the main limitation in the current Futhark compiler.  It is hard to circumvent (but do read [When Things Go Wrong](https://futhark-book.readthedocs.io/en/latest/practical-matters.html#when-things-go-wrong).

This error typically occurs when there is a loop or branch inside of a parallel construct (typically a `map`) where the size of the array is not the same for each iteration of the outer `map` (so, an occurrence of irregular parallelism).  Sometimes, this is just because the Futhark is not smart enough to see that it really is regular.  More often, it is because the algorithm is truly irregular.  It can help to go through the program and think, for each nested `loop` or `if`, whether the sizes of the arrays involved are invariant to the parallel levels on top.  Often, the problem is something fairly trivial, where have e.g. a default case that returns an empty array:

```
if b then e else []
```

This is problematic, because `e` and `[]` probably return arrays of different sizes.  In such cases, it is necessary to know the size of the array produced by `e` (let's say it's `n`) and write:

```
if b then e else replicate n 0
```

(Or in some other way enforce that the arrays end up as the same size.)

Do you have an example of the problematic code?

**Comment by sigismundearbuthnotte** [comment]
Thanks for the detailed reply.  I won't burden you with the code (just yet!) as there's a lot of it (it's auto-generated).
However, you have given me enough to work on FTB.  In particular, I DO have a "if b then e else []" so I'll start there.

Thank you.

**Comment by athas** [comment]
For debugging, it can be a good idea to annotate `let` or `loop`-bound arrays with the sizes you *expect* them to have:

```
let (arr: [n]f32) = if b then e1 else e2
```

`futhark c` can always compile this (barring new compiler bugs; please report them too), and if the size constraint is violated at run-time, it will produce an error saying exactly where it went wrong.  That's a lot more helpful than the incomprehensible mess emitted by `futhark opencl`.
