### ISSUE TITLE
ISPC backend

### ISSUE THREAD

**Issue by csabahruska** [diku-dk/futhark#733]
Hi,

How hard would it be to target [Intel SPMD Program Compiler](https://ispc.github.io/) as a CPU backend?

**Comment by athas** [comment]
I've thought about this before.  I don't think it would be particularly hard.  Most of the current GPU-focused pipeline could be used as-is, and at the end where parallel buildling blocks are turned into GPU kernels (and lots of bookkeeping-boilerplate), they'd be turned into ISPC programs instead.

**Comment by csabahruska** [comment]
How many IR layers does Futhark have?
Is there a compiler pipeline/architecture overview?

**Comment by athas** [comment]
It depends on how you count - I would say there are the following:

1) Source language
2) Core IR with SOACs
3) Core IR with flat-parallel kernel constructs
4) Core IR with explicit memory information
5) Imperative IR ("ImpCode")

There is not currently any pipeline architecture overview.  The closest thing would be the actual [definition of the GPU pipeline](https://github.com/diku-dk/futhark/blob/master/src/Futhark/Passes.hs#L100).

**Comment by athas** [comment]
I did some experiments based on the multicore backend, where I extracted the parloop functions into separate ISPC source files, which I then compiled separately and then linked with the original program.  This is surprisingly painless, since all we do is pass primitive data and pointers around.  I tried two programs, both of which I would consider best-case applications, since they are rather compute-intensive.  The performance results are unfortunately mixed.

[This Mandelbrot program](https://github.com/diku-dk/futhark-benchmarks/tree/master/accelerate/mandelbrot) gives almost 3x speedup over multicore execution by itself.  This is pretty good.

[This ray tracer](https://github.com/athas/raytracers/tree/master/futhark) unfortunately gives a significant *slowdown* (almost x4).  It's not clear to me why.  It's possibly due to the gather operations necessary to traverse the BVH, but I'm surprised that it would be *slower* than completely scalar execution.  I'm not sufficiently strong in x86 SIMD assembly to figure out what goes wrong, but the generated assembly has a rather large number of spills (36% of *static* instructions are spills or reloads, compared to 20% for Mandelbrot).  It actually uses over 8KiB of stack space just for spills (5KiB for Mandelbrot).

I'm fairly confident than an ISPC backend is a good idea, but it will probably be an *interesting* project to make it reliably fast.

**Comment by csabahruska** [comment]
Are the cache miss and hits are similar in the two examples?

**Comment by athas** [comment]
For mandelbrot it's about the same, and the main difference is that the ISPC version has over an order of magnitude fewer branches (because they are turned into vector instructions instead):

```
$ futhark dataget mandelbrot.fut '800i32' | perf stat -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./mandelbrot -r 10 >/dev/null

 Performance counter stats for './mandelbrot -r 10':

         1,489,224      cache-references:u                                          
           176,116      cache-misses:u            #   11.826 % of all cache refs    
     1,291,429,654      cycles:u                                                    
       921,864,616      instructions:u            #    0.71  insn per cycle         
        33,602,798      branches:u                                                  
             1,123      faults:u                                                    
                 0      migrations:u                                                

       0.026312760 seconds time elapsed

       0.366651000 seconds user
       0.002031000 seconds sys


$ futhark dataget mandelbrot.fut '800i32' | perf stat -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./mandelbrot-orig -r 10 >/dev/null

 Performance counter stats for './mandelbrot-orig -r 10':

         1,684,446      cache-references:u                                          
           258,205      cache-misses:u            #   15.329 % of all cache refs    
     3,549,259,737      cycles:u                                                    
     4,206,419,500      instructions:u            #    1.19  insn per cycle         
       572,702,965      branches:u                                                  
             1,111      faults:u                                                    
                 0      migrations:u                                                

       0.065079294 seconds time elapsed

       0.988636000 seconds user
       0.013021000 seconds sys
```

For the ray tracer, the number of cache misses is about the same, but the ISPC version uses way more clock cycles.  I think it's simply a case of bad code generation.

```
$ perf stat -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./main -r 10 >/dev/null

 Performance counter stats for './main -r 10':

        14,182,736      cache-references:u                                          
           817,704      cache-misses:u            #    5.765 % of all cache refs    
    11,248,950,487      cycles:u                                                    
    11,798,731,019      instructions:u            #    1.05  insn per cycle         
       412,569,810      branches:u                                                  
               288      faults:u                                                    
                 0      migrations:u                                                

       0.398113297 seconds time elapsed

       3.137669000 seconds user
       0.017009000 seconds sys


$ perf stat -B -e cache-references,cache-misses,cycles,instructions,branches,faults,migrations ./main-orig -r 10 >/dev/null

 Performance counter stats for './main-orig -r 10':

         8,622,395      cache-references:u                                          
           619,290      cache-misses:u            #    7.182 % of all cache refs    
     5,581,579,156      cycles:u                                                    
     8,240,177,877      instructions:u            #    1.48  insn per cycle         
       847,896,327      branches:u                                                  
               329      faults:u                                                    
                 0      migrations:u                                                

       0.104613789 seconds time elapsed

       1.544765000 seconds user
       0.052433000 seconds sys
```

**Comment by csabahruska** [comment]
Just for curiosity how the examples perform in comparison with Futhark if you compile them with ISPC's (new) GPU backend?
https://ispc.github.io/ispc_for_gen.html

**Comment by athas** [comment]
Unfortunately I don't have a machine with oneAPI.

**Comment by maedoc** [comment]
> This ray tracer unfortunately gives a significant slowdown

Maybe worth looking at [this project](https://github.com/embree/embree) which does ray-tracing in ISPC, to avoid trying bothering with the assembly, and just see how they set it up in ISPC?
