### ISSUE TITLE
Fix global memory fences in OpenCL kernels on NVIDIA

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#734]
I [found out an awful truth](https://github.com/diku-dk/futhark/commit/49214b807a9bffc339c2c4bc1ac4610125e41509#commitcomment-32890492) that on NVIDIA GPUs, our supposed global memory fences only take effect within the current workgroup (or more likely, SM).  This is *not* an NVIDIA bug - it is us who are technically violating the OpenCL spec.  The barriers work fine with the CUDA backend, because CUDA has fewer restrictions on cross-workgroup synchronisation.  The solution is to generate generate inline assembly with an explicit `membar.gl` instruction when we are running on an NVIDIA GPU.  I think the solution is for us to define our own wrapper function:

```
void mem_fence_global() {
#ifdef NVIDIA
  asm("membar.gl;");
#else
  mem_fence(CLK_GLOBAL_MEM_FENCE);
#endif
}
```

The only trick is to have some sort of preprocessor symbol (here, NVIDIA) that is set when we detect an NVIDIA platform.  I couldn't find any documentation about NVIDIA setting this themselves, so we'll have to invent our own policy.

**Comment by rowanG077** [comment]
I think the same underlying issue is biting us in the ass with Mesa Rusticl on Apple GPUs. We are getting completely incorrect results from a kernel on an Apple M2 Max, while the same program produced correct results using the C backend and OpenCL on an NVIDIA GPU.

Environment:

- Futhark 0.26.3
- Mesa/Rusticl 26.1.4
- Apple M2 Max (G14C B1)
- Asahi Linux

Minimal reproducer:

```
let min_max_nonzero (a: (u16, u16)) (b: (u16, u16)): (u16, u16) =
  let (amin, amax) = a
  let (bmin, bmax) = b
  let min =
    if amin == 0 then bmin
    else if bmin == 0 then amin
    else u16.min amin bmin
  in (min, u16.max amax bmax)

entry main (n: i64): (u16, u16) =
  let values =
    map
      (\i ->
        if i == 0 then 30483u16
        else if i == n - 1 then 38172u16
        else 32000u16)
      (iota n)
  in reduce_comm min_max_nonzero (0u16, 0u16) (map (\x -> (x, x)) values)
```

The C backend produces the expected result:

```
$ futhark c repro.fut -o repro-c
$ echo 6400000i64 | ./repro-c
30483u16
38172u16
```

OpenCL on Asahi/Rusticl produces an incorrect result:

```
$ futhark opencl repro.fut -o repro-cl
$ echo 6400000i64 | ./repro-cl
2u16
32000u16
```

The exact incorrect values can vary between runs and with the number of workgroups.

OpenCL on NVIDIA produces the expected result:

```
$ futhark opencl repro.fut -o repro-cl
$ echo 6400000i64 | ./repro-cl
30483u16
38172u16
```

I narrowed this down by changing only the number of workgroups used by the generated segmented reduction. With the same 6.4-million-element input and a workgroup size of 256:

```
$ echo 6400000i64 | ./repro-cl \
    --param main.segred_num_tblocks_5974=1
30483u16
38172u16
```

As soon as two or more workgroups participate, the result becomes incorrect. Some observed results were:

workgroups=1:   30483 38172
workgroups=2:   30483 32000
workgroups=4:   2 38172
workgroups=8:   2 32000
workgroups=120: 2 32000

**Comment by athas** [comment]
A similar fix ought to be possible, if a Rusticl allows inline assembly and an appropriate instruction is available. Rusticl is based on SPIR-V, right? Sadly I do not have an Apple device available.

**Comment by rowanG077** [comment]
I don't think you can do that, I tested a few things and it doesn't seem possible.. I did check that replacing the fence with `atomic_work_item_fence` and the completion counter with `atomic_fetch_add_explicit` works. But that is openCL 2.0...

**Comment by athas** [comment]
Which platforms do not support OpenCL 2.0? Only NVIDIA? If so, it is not a problem, as we do the inline assembly trick on NVIDIA. We could also #ifdef based on OpenCL support. I would accept a PR that used `atomic_work_item_fence` and `atomic_fetch_add_explicit`.
