### ISSUE TITLE
field/module access confusion?

### ISSUE THREAD

**Issue by mt-caret** [diku-dk/futhark#770]
I've just started to write Futhark, and I'm having a great time; thanks for the amazing work!

I've been trying to write a naive attempt at creating u256s in Futhark, and here's how far I've gotten:

```
module u256 = {
  type t = [4]u64

  let wrap (n: u64): t = [0, 0, 0, n]

  let i8   = wrap <-< u64.i8
  let i16  = wrap <-< u64.i16
  let i32  = wrap <-< u64.i32
  let i64  = wrap <-< u64.i64

  let u8   = wrap <-< u64.u8
  let u16  = wrap <-< u64.u16
  let u32  = wrap <-< u64.u32
  let u64  = wrap <-< u64.u64

  --let f32  = wrap <-< u64.f32
  --let f64  = wrap <-< u64.f64

  --let bool = wrap <-< u64.bool
}
```

The problem is, when I uncomment any of the last three declarations, I get the following error (modulo names and line numbers):

```
$ futhark c u256.fut
Error at u256.fut:16:23-29:
Couldn't match expected type `(x: u64) -> []u64' with actual type `{f32: t₃}'.
When matching type
  (x: u64) -> []u64
with
  {f32: t₃}

If you find this error message confusing, uninformative, or wrong, please open an issue at https://github.com/diku-dk/futhark/issues.
```

It took me a while to realize that it seems like the compiler is seeing `u64.f32` as accessing a record with the field `f32` (and does so on the 9th appearance). Aliasing the module like so:

```
module u256 = {
  type t = [4]u64

  let wrap (n: u64): t = [0, 0, 0, n]

  module u = u64

  let i8   = wrap <-< u.i8
  let i16  = wrap <-< u.i16
  let i32  = wrap <-< u.i32
  let i64  = wrap <-< u.i64

  let u8   = wrap <-< u.u8
  let u16  = wrap <-< u.u16
  let u32  = wrap <-< u.u32
  let u64  = wrap <-< u.u64

  let f32  = wrap <-< u.f32
  let f64  = wrap <-< u.f64

  let bool = wrap <-< u.bool
}
```
fixes the errors; I'm not sure if this is just me doing something stupid, or a bug in the compiler (experience suggests the former).

```
$ futhark --version
Futhark 0.11.1
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by athas** [comment]
This is because modules and ordinary values occupy the same name space.  Your definition of the `u64` function shadows the module `u64`.  The reason they occupy the same name space is that `x.y` is otherwise ambiguous (is it accessing a record or a module?).  [I wrote a little about it once](https://futhark-lang.org/blog/2017-11-11-dot-notation-for-records.html).

In practice it is almost never a problem.  In fact, the only times I remember being annoyed by it is exactly when implementing numeric modules.  Sometimes you can work around it by reordering your definitions.  In other cases, your workaround is correct, and [I do the same thing in the basis library](https://github.com/diku-dk/futhark/blob/87af51d042508fbfcc405b6cadfdd14fa8699445/futlib/math.fut#L775).

**Comment by mt-caret** [comment]
Yeah, I just realized that was the problem; thanks for the help!
