### ISSUE TITLE
pyopencl python backend discreptancy?

### ISSUE THREAD

**Issue by mt-caret** [diku-dk/futhark#771]
Hi, I've been trying to test a u256 implementation of mine via hypothesis (python's quickcheck) and the pyopencl backend when I came across some weird behavior, possibly relating to serialization across the futhark(opencl)-python boundary. To investigate, I switched over to using the python backend when I found that I get different results when calling the same function with the same arguments.

Here's a minimum reproducible example:
python: https://gist.github.com/mt-caret/49d61d22a7577c4e8095f4fc92f86a22
futhark: https://gist.github.com/mt-caret/d6fbde84f10b1e420b035f4e31df65c5
pyopencl backend output: https://gist.github.com/mt-caret/b08eb5f5198a9c089cd1933815432a51
python backend output: https://gist.github.com/mt-caret/df21a098e32ffcfa534c6ee7c9aa350e

In this case, are differing results across backends expected behavior?

```
$ futhark --version
Futhark 0.11.1
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by mt-caret** [comment]
I just saw https://github.com/diku-dk/futhark/issues/765 and I realized that the issue might not be in serialization, so I added the following line to the Futhark code:

```
entry main: [8]u32 = pack_unpack_roundtrip [1, 0, 0, 0, 0, 0, 0, 0]
```

and running this gives the following:

```
$ futhark pyopencl --safe u256.fut && ./u256
/nix/store/zfnva27rkm8lb9b793qqw48yzbp7v7qn-python3.7-pyopencl-2018.2.3/lib/python3.7/site-packages/pyopencl/__init__.py:232: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  "to see more.", CompilerWarning)
[1u32, 1u32, 0u32, 0u32, 0u32, 0u32, 0u32, 0u32]

$ futhark c --safe u256.fut && ./u256
[1u32, 1u32, 0u32, 0u32, 0u32, 0u32, 0u32, 0u32]

$ futhark run u256.fut && ./u256

[1u32, 1u32, 0u32, 0u32, 0u32, 0u32, 0u32, 0u32]

$ futhark run u256.fut <<< ""

[1u32, 0u32, 0u32, 0u32, 0u32, 0u32, 0u32, 0u32]
```

I'm not really sure what's happening here...

**Comment by athas** [comment]
For the `python` backend, you are definitely encountering #765, which is not yet fixed in any released version.

For the others, I'm not sure what is going on.  I will investigate.

**Comment by athas** [comment]
The root cause of this issue is the bitshift, which is sometimes done with a right-hand side of greater than 31.  For performance reasons, the Futhark compiler translates most scalar operations to whatever the underlying machine (or C) does.  In C, right shifting is undefined if the shift amount is equal or greater to the number of bits in the type.  IIRC, on most architectures the surplus bits are just ignored, so shifting by 32 is equal to shifting with 0.  The interpreter does not use a hardware shift, so it behaves differently.

There are several similar related issues that I have thought about before.  For example, signed integer overflow is also undefined in C, but Futhark lets you do it.  It's not clear to me how (or if) this should be resolved, as actively checking for these situations may be unacceptably slow.  In any case, these cases of undefined behaviour are rare: your program is the first one I've seen to actually encounter one in practice.

To directly address your problem, define your own bitshift function:

```
let shiftright (x: u32) (y: u32) = if y > 31 then 0 else x >> y
```

**Comment by mt-caret** [comment]
Aha, I'm sorry for the trouble, thanks!
