### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by mt-caret** [diku-dk/futhark#774]
running `futhark c reproduce.fut` with [this](https://gist.github.com/mt-caret/d6fbde84f10b1e420b035f4e31df65c5) and [this](https://gist.github.com/mt-caret/707702863bfebf36a0a9eaa1174efb0b) results in the following error:
```
Internal compiler error.
Please report this at https://github.com/diku-dk/futhark/issues.
Type error after pass 'In-place lowering':
In function main
When checking function body
In expression of statement {[1024i32][8i32]i32 res_5745}
Inside the loop body
In expression of statement {[1024i32][8i32]i32 lw_dest_5787}
Inside the loop body
In expression of statement {[1024i32][8i32]i32 lowered_array_updated_5794}
Type error:
The target of an Update must not alias the value to be written.
```

```
$ futhark --version
Futhark 0.11.1
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by athas** [comment]
While this bug is fixed, I will also advice against your implementation of the `u256` module.  Performing parallel operations on small arrays is a bad idea.  A better representation is to use a tuple of eight values.  See [this post](https://futhark-lang.org/blog/2019-01-13-giving-programmers-what-they-want.html) for the reason (and for why the compiler does not just do it for you).

**Comment by mt-caret** [comment]
I'll take a look; thanks!
