### ISSUE TITLE
Add attribute system

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark#801]
I'd like to soon turn on incremental flattening by default.  One problem is that compile times increase significantly - partly because multiple versions are necessary, but also partly because we generate versions that *we* know will never be useful, but the compiler does not know.  For example, LocVolCalib has this `main`:

```
let main (outer_loop_count: i32) (numX: i32) (numY: i32) (numT: i32)
         (s0: f32) (t: f32) (alpha: f32) (nu: f32) (beta: f32): []f32 =
  ...
```

*We* know that `outer_loop_count` will never be sufficiently parallel on its own, but the compiler does not, so it generates a version of the code that is a big `map` with a huge sequential computation inside.  It would be nice if we could hint this to the compiler, and so not have it waste time generating (and subsequently optimising) that version.  I think this should be done by extending the notation for entry points.  Here's a draft of what it could look like:

```
let main (outer_loop_count: i32) (numX: i32) (numY: i32) (numT: i32)
         (s0: f32) (t: f32) (alpha: f32) (nu: f32) (beta: f32): []f32
  with insufficient_parallelism outer_loop_count =
  ...
```

The `with insufficient_parallelism outer_loop_count` is not an ordinary expression, but an annotation using some grammar for hints.  Here we assert that the size `outer_loop_count` never provides enough parallelism on its own.  For a matrix multiplication where we know the outer sizes are always sufficient, we could put:

```
let main [n][m][l] (x: [n][l]i32) (y: [l][m]i32): [n][m]i32
  with sufficient_parallelism (n*m) =
  ...
```

While I don't intend to use this notation for anything except multiversioning hints in the short term, in the long term it might also be the place we put invariants for refinement types or Cosmin's old ideas about shape annotations.

I'm willing to bike shed the syntax.  In the draft above, I made these hints a first-class syntactical construct (that occurs before the `=` in an entry point definition).  Other languages might hide them in comments, but I've never liked that much.

**Comment by athas** [comment]
Another approach, which will require no syntactic changes, is to just treat the hints as functions whose result we ignore:

```
let main (outer_loop_count: i32) (numX: i32) (numY: i32) (numT: i32)
         (s0: f32) (t: f32) (alpha: f32) (nu: f32) (beta: f32): []f32 =
  let _ = insufficient_parallelism outer_loop_count
  in ...
```

That will let us prototype the idea without committing to any syntax.  The internaliser will recognise these function calls and add annotations to the IR for the entry point, but they will not have any other effect.

**Comment by Munksgaard** [comment]
I like the initial syntax you proposed, but I can definitely see the benefit of using your second approach for a start. Would the second approach allow us to prototype things like shape annotations and refinement types as well? Or would that be more difficult, since it applies to the type of the function?

**Comment by athas** [comment]
I guess it could also be used to prototype refinement types, but I suspect refinement types are most useful when you also have a specialised notation (hence why Liquid Haskell stuffs them into comments).

**Comment by Munksgaard** [comment]
One argument for putting stuff like this in comments is that it makes the job of futhark-mode.el and similar tools simpler, otherwise they have to start parsing entirely new syntax. 

Rust takes a different approach and uses annotations 

```
#[cfg(not(feature = "foo"))]
#[derive(Debug)]
struct foo { ... }
```

I think the primary benefit is that the annotations are visually distinct from comments, but the annotation syntax is relatively simple and so it doesn't put too much of a burden on parsers and the like.

**Comment by athas** [comment]
I think taking Rust's annotation syntax is best.  It may also help for a few other things (such as `noline` attributes) that I've wanted.

**Comment by athas** [comment]
@Munksgaard, do you understand why Rust distinguishes between inner and outer attributes?  In Futhark, could we not allow merely

```
let main (outer_loop_count: i32) (numX: i32) (numY: i32) (numT: i32)
         (s0: f32) (t: f32) (alpha: f32) (nu: f32) (beta: f32): []f32 =
  #[par_insuff(outer_loop_count)]
  let ...
```

I'm also not sure where attributes should be allowed.  Allowing them before *everything* sounds nice, but it's implementation-wise a bit awkward.  Maybe we can live with only allowing them before function definitions:

```
#[par_insuff(outer_loop_count)]
let main (outer_loop_count: i32) (numX: i32) (numY: i32) (numT: i32)
         (s0: f32) (t: f32) (alpha: f32) (nu: f32) (beta: f32): []f32 =
  let ...

```

It's a bit clumsy that we refer to a variable before it is brought into scope, but I guess not the end of the world.

**Comment by Munksgaard** [comment]
> @Munksgaard, do you understand why Rust distinguishes between inner and outer attributes? In Futhark, could we not allow merely

As you've noticed, in Rust `#![...]` denotes an attribute that applies to the surround context, while `#[...]` applies to the next item in the code. The prior notation are often used to apply attributes to modules (which are just files), so you'll have something like the following at the beginning of the module file:

```rust
#![allow(unused_variables)]
```

Because a module is just a file, there's no explicit module declaration at the beginning of the file to apply the attribute to, so we need the `#![...]` syntax.

The `#[...]` syntax applies to the next "item" in the code, most often a function, struct or trait declaration, and it is often used for `#[derive(...)]` annotations. For instance:

```rust
#[derive(Debug)]
struct Foo {
    bar : i32,
}
```

You cannot put that derive annotation inside the struct declaration, so we need the `#[...]` notation.

As another example, the following two bits of code are semantically equivalent:

```rust
#[allow(unused_variables)]
fn main() {
    let x = 1f32;
    let y = 2;
    println!("Hello, world! {:?}", x/0.0);
}
```

```rust
fn main() {
    #![allow(unused_variables)]
    let x = 1f32;
    let y = 2;
    println!("Hello, world! {:?}", x/0.0);
}
```

They both specify that inside the main function, the compiler doesn't need to warn us about any unused variables (`y` in this case).

Finally, the `#[...]` and `#![...]` syntax is also used to apply documentation to different items. For instance, a `#![doc(...)]` annotation inside a module will become module documentation, while a  `#[doc(...)]` annotation before a function becomes function documentation. The `///` and `//!` notation you may have seen are merely syntactic sugar for doc annotations. 

With regards to Futhark, I think it depends on what else we want to use the annotations for. As a way of saying "this value will never have enough parallelism, so don't bother", I'm sure it would be enough to just use the `#[...]` syntax, in whatever form we want.

I agree that it's a bit weird to refer to variables before they're brought in to scope. Would it make more sense to apply the attribute where Futhark will try to parallelize? For instance:

```futhark
entry mapscan2 [k] (ns: []i32) (xs: [k]i32)
             : [k]i32 =
  loop xs for n in ns do
  let m = k / n
  let xss' = unflatten m n xs
  let xss =
    #[par_insuff(xss')]
    map2 (\row i ->
            loop row for _ in 0..<64 do
              let row' = map (+i) row
              in scan (+) 0 row'
         )
         xss' (iota m)
  in flatten_to k xss
```

I'm not sure exactly what the semantics would be, or how to generalize it, but here the annotation applies to the `map2`, telling the compiler not to try to parallelize it because of `xss'`. There may be problems with this approach due to how eager Futhark is to rewrite and rearrange code.
