### ISSUE TITLE
Exponential compile time with GPU pipeline

### ISSUE THREAD

**Issue by nqpz** [diku-dk/futhark#805]
I get very long compile times when I run `time futhark dev -s --gpu expo.fut >/dev/null` with futhark from git 89f27f6.

The attached file `expo.fut` has 16 calls to `next` in its `calc` function.
Here are my measurements of the compile times (on my laptop) for different numbers of `next` calls (to reproduce, just remove $16 - n$ lines of the form `let (s, _) = next s`):

```
13:  1.3 seconds
14:  2.9 seconds
15:  7.5 seconds
16: 18.1 seconds
17: 50.5 seconds
```

I'm not sure why this happens.  Maybe it has something to do with the simplifier?

[expo.fut.txt](https://github.com/diku-dk/futhark/files/3833581/expo.fut.txt)

**Comment by athas** [comment]
For mysterious reasons, simplification seems to take a very long time after kernel extration.

**Comment by athas** [comment]
Ah, this is because it ends up constructing an exponentially-sized `PrimExp` (these are always considered fully inlined).  I suspect it runs up against the sanity check in `simplifyIndexing` that only manifests PrimExps if they are less than 10 nodes, as that still requires us to count the entire size of the PrimExp.
