### ISSUE TITLE
Add break on floating-point exceptions in the repl

### ISSUE THREAD

**Issue by he-la** [diku-dk/futhark#839]
It would be helpful to have the repl automatically break execution when encountering floating-point exceptions like divide by zero, nan, etc. This was previously mentioned in #119 and dismissed because it would be hard to implement on the GPU, but since all debugging is done through the REPL now it seems like a good time to reconsider this decision.

This should be straightforward to implement by manipulating the floating-point environment to enable exceptions (see e.g. the `altfloat` package which implements fenv support). Unfortunately I'm a bit too overwhelmed by the futhark codebase to do it myself.

As an off-topic remark: Thank you for working on futhark, it has been tremendously helpful!

**Comment by athas** [comment]
I think this would be a good addition.  Unfortunately, we cannot directly use real floating-point exceptions (as in `altfloat`) because the Futhark interpreter itself is pure, and so cannot catch IO exceptions.  The solution is thus to make an explicit check after each potentially NaN-causing operation.

The implementation shouldn't be difficult, as the interpreter is a pretty isolated piece of code.  There is the [actual interpreter](https://github.com/diku-dk/futhark/blob/master/src/Language/Futhark/Interpreter.hs) and [the `repl` subcommand](https://github.com/diku-dk/futhark/blob/master/src/Futhark/CLI/REPL.hs).

The definitions to change are in the [initial context](https://github.com/diku-dk/futhark/blob/master/src/Language/Futhark/Interpreter.hs#L948), which ultimately contains Haskell functions that run in the `EvalM` monad.  For example, [this](https://github.com/diku-dk/futhark/blob/master/src/Language/Futhark/Interpreter.hs#L1124-L1135) is where builtin arithmetic functions (but not operators) like `f32.sqrt` are handled.  This is where a conditional `break` could be inserted.

There is a design question to be answered though: should we break on every operation that returns NaN, or only on those where all of the inputs are non-NaN already?  I.e. is NaN propagation interesting or just noise?  Maybe it should be configurable?  I can imagine a command `:break +nan` that will enable breaking every time a NaN is produced (and `:break -nan` to turn it off), and a `:break :nan-new` that only breaks when a NaN is produced from non-NaN inputs.  (I'm willing to bikeshed this part of the UI.)

**Comment by he-la** [comment]
> I.e. is NaN propagation interesting or just noise?

Personally I've mostly tried finding the root cause of nans and was less interested in their propagation, but it seems like a good idea to have the option of doing both. I'd however prefer the command `:break +nan-propagate` and `:break +nan-new` to make this more explicit.

Thank you for the pointers to the source, I'll try to implement this soon!

**Comment by he-la** [comment]
I've tried to get this working, but to no avail. I fear my amateur haskell is not quite up to the task.

**Comment by athas** [comment]
I am finishing up an implementation of this.  Just missing the actual toggle in `futhark repl`.  I think I will only add `:break +nan` for now, and it will only break on *new* NaNs (where none of the inputs to the operation were themselves NaNs).  I think that is the most useful case.  Propagation is kind of hard to nail down.  Is returning NaN from an `if` a NaN propagation?

**Comment by athas** [comment]
I'll do it by adding a command called `:nanbreak` that just toggles the behaviour.
