### ISSUE TITLE
How to benchmark the futhark compiler?

### ISSUE THREAD

**Issue by flip111** [diku-dk/futhark#841]
Is there anything in place to benchmark the compiler itself?
Is there anything to run all tests?

Maybe some simple things can get a bit more performance (which is always nice). Like tuning garbage collector and passing `-O2` flag. But for that it needs benchmarks to know for sure.

**Comment by athas** [comment]
Full benchmarking?  No.  But if run with `-v`, the compiler will print delta times for the various passes.  That's how I identify which passes to speed up when I feel the compiler has gotten too sluggish.  (Note that the time on a line refers to the time taken by the pass on the *preceding* line.)

I generally use compilation time of the [various benchmarks](https://github.com/diku-dk/futhark-benchmarks) to check how well we are doing.  I tend to use the following three:

* [LocVolCalib](https://github.com/diku-dk/futhark-benchmarks/blob/master/finpar/LocVolCalib.fut) as a benchmark program that isn't totally trivial, but still fairly small
* [Myocyte](https://github.com/diku-dk/futhark-benchmarks/blob/master/rodinia/myocyte/myocyte.fut) as a large and very ugly program that takes a long time to compile because of a large amount of inlining
* [Heston](https://github.com/diku-dk/futhark-benchmarks/blob/master/misc/heston/heston32.fut) for another large program that takes a long time to compile because of its inherent complexity and significant use of abstraction

**Comment by flip111** [comment]
I was also asking about tests because some compiler flags might change the behavior of the program and it would be good to run all tests

**Comment by athas** [comment]
No compiler flags change the behaviour of the program (except for `--safe`, kind of).  That's very intentional design.  The only thing that matters is choice of backend.

**Comment by flip111** [comment]
I meant compiler flags of GHC. I'm not sure how much of an issue this is with GHC. But even with GCC i know a lot of stories where programs behave differently with optimizations turned on or off. Just saying it would be good when changing GHC flags to run all futhark tests to see if everything is in the green.

**Comment by athas** [comment]
It would be a GHC bug if the Futhark compiler changed its actual behaviour (except performance).  I haven't played much with the flags, except for once noting that performance is quite sensitive to GC tweaks.

**Comment by flip111** [comment]
Yes GC tuning might be worthwhile to set the default [H value](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag--H%20[%E2%9F%A8size%E2%9F%A9]) and [A value](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag--A%20%E2%9F%A8size%E2%9F%A9) this can help https://hackage.haskell.org/package/ghc-gc-tune
