### ISSUE TITLE
indices function crashing Futhark REPL

### ISSUE THREAD

**Issue by philiplassen** [diku-dk/futhark#874]
I was trying to see what the *indices* function from futlib/array did, and was testing it in the REPL. I got the following Error
```
~$ futhark repl
|// |\    |   |\  |\   /
|/  | \   |\  |\  |/  /
|   |  \  |/  |   |\  \
|   |   \ |   |   | \  \
Version 0.15.1.
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.

Run :help for a list of commands.

[0]> indices
Inferred type of expression: [n₀]t₁ -> *[n₀]i32
The following types are ambiguous: n₀, t₁
[1]> indices [1, 2, 3, 4]
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
eval: nonsensical type for integer literal: t₅
CallStack (from HasCallStack):
  error, called at src/Language/Futhark/Interpreter.hs:803:10 in fthrk-0.15.1-47358335:Language.Futhark.Interpreter
```

**Comment by athas** [comment]
This was fixed in https://github.com/diku-dk/futhark/commit/61d8dde0c0a450e3892e94011c6293f811642dc8.

The problem exists for *any* overloaded numeric literal in the REPL.  If you just put in `123`, you will see the same crash.  Oops.  I intend to make a new release during the weekend; feel free to compile Futhark from Git until then.
