### ISSUE TITLE
Executables ignore extra arguments

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#877]
I was surprised by the output of the following snippet (stripped down example from the original code, which occurred when I was removing arguments from a function during refactoring):
```
-- ==
-- compiled input { 0 } auto output
entry main = 0
```
Even though there's an argument mismatch, no errors are thrown. After playing around with the executables, it seems that extra input is ignored. In this case, `main` has no arguments, so it ignores everything on stdin.

This makes sense, as it allows the executables to run even if the input isn't perfect. It looks a bit weird written as a test case, though. Maybe there should be a warning?

**Comment by athas** [comment]
It's tricky to do anything about this one.  `futhark test` itself cannot warn, because it does not actually know anything about the program being tested (it doesn't look at the types or anything).  That's by design.  I think the best way to handle this is for the executables to insist on EOF on stdin before they start running code, and error out if there's anything but whitespace after the last value.  I think that will not break anything.
