### ISSUE TITLE
hPutBuf: resource exhausted (No space left on device)

### ISSUE THREAD

**Issue by NPN** [diku-dk/futhark#896]
I was trying to benchmark on a disk with very little free space and got this error:
```
Compiling test.fut...
futhark: ./data/[4100][4000]u8366844-0.in: hPutBuf: resource exhausted (No space left on device)
Internal compiler error (unhandled IO exception).
Please report this at https://github.com/diku-dk/futhark/issues
thread blocked indefinitely in an MVar operation
```
I don't think this kind of error can be gracefully recovered from, but I figured I would report it anyway (if only to have it in the issue tracker for other people to search and find).

**Comment by athas** [comment]
`futhark test` and `futhark bench` have a nasty habit of reporting that MVar error whenever a worker thread encounters a catastrophic problem (like here).  Fixing it has been low on the list because there is fortunately always a mostly sensible error message beforehand, but I guess I should see if there's a more graceful way of catching this.
