### ISSUE TITLE
Warn on out-of-bounds literals

### ISSUE THREAD

**Issue by mb64** [diku-dk/futhark#979]
Currently, the Futhark compiler accepts, without any messages, code like

```futhark
let positive_number : i32 = 6789012345
let negative_number : u32 = -12 
let finite_number : f32 = 1e40

entry main : (i32, u32, f32) = (positive_number, negative_number, finite_number)

-- Output:
-- -1800922247i32
-- 4294967284u32
-- f32.inf
```

I tried implementing warnings myself, and ended up with 
```haskell
literalOverflowCheck :: ASTMappable x => x -> TypeM ()
```
which I added to `checkFunDef` and `checkOneExp`, but it didn't seem to actually run for my simple test-case.

If I could get some guidance as to the best way to add, I would love to make a PR.

**Comment by athas** [comment]
We should definitely warn about this, but it is a little tricky, since at the time we are first checking the integer literal, we do not yet know its eventual type.  I can see two ways of doing this.

0) For [overloaded type variables](https://github.com/diku-dk/futhark/blob/530a55912955d2c818c624f35f5e174849772594/src/Language/Futhark/TypeChecker/Unify.hs#L130), also keep track of any literals of that type, and when we finally instantiate the type variable with a specific type, check that it's big enough for all the literals.  I don't like this much, as it requires modification of deep type system machinery (which is complex enough already).

1) After type checking a function, do a pass where we check that all literals have been inferred to have an acceptable type.  We already [do a similar pass](https://github.com/diku-dk/futhark/blob/master/src/Language/Futhark/TypeChecker/Terms.hs#L2467) to check various other safety properties.  I don't think adding another one is a problem.  If we think it's too wasteful to do an entire pass just for this, it wouldn't be hard to make the existing [causality check pass](https://github.com/diku-dk/futhark/blob/530a55912955d2c818c624f35f5e174849772594/src/Language/Futhark/TypeChecker/Terms.hs#L2344) do double duty here.  We could also have the type checker monad (TermTypeM) collect all literals and their type variables, and then at the end verify that they all have been instantiated with acceptable types.  That would require extending [the type checker state](https://github.com/diku-dk/futhark/blob/530a55912955d2c818c624f35f5e174849772594/src/Language/Futhark/TypeChecker/Terms.hs#L311).

**Comment by mb64** [comment]
I tried [adding `literalOverflowCheck body''` right after `causalityCheck body''`](https://github.com/mb64/futhark/blob/warn-bad-literals/src/Language/Futhark/TypeChecker/Terms.hs#L2504), but that seemed to work only in some cases:
```futhark
let f x : i32 = 9876543210 + x -- Warns
let var : i32 = 9876543210 -- Does not warn
```
I'm not sure why – do constants not go through `checkFunDef`?

It might also make some sense to run the overflow pass after some simple constant folding has already taken place, to make it easier to handle `-12` actually being `Negate (+12)`.

**Comment by athas** [comment]
They do.  You're running into a subtle detail of `astMap`, which is that it does not apply do its *immediate* argument, but only to its subexpressions.  You need to call your `check` function on the original input as well.  `astMap` also does not automatically recurse, so you need to apply it to the argument in the wildcard case.

**Comment by mb64** [comment]
Thanks for the help.  I did indeed misunderstand `astMap`, but I think I've got it to (mostly) work now.  My fork now says:
```
Warning at test.fut:1:29-38:
  Literal 6789012345 out of bounds for inferred type i32

Warning at test.fut:2:29-29:
  Literal -12 out of bounds for inferred type u32

Warning at test.fut:3:27-30:
  Literal 1.0e40 out of bounds for inferred type f32
```
The remaining issues I want to fix with it before I make a PR are:
 * Location info for negated integers only points to the minus sign.  It needs to merge the location info from `Negate (IntLit _ _ loc1) loc2` somehow.
 * Diagnostic tests: there should be a test to make sure the warnings run, presumably something like
```futhark
-- Warn on overflowing literals
--
-- ==
-- warning: out of bounds

let main : u8 = 257
```
(I'm not familiar with the test suite, so I'm not sure of the exact syntax, or what file to put it in.)
 * Merge with causality checks? You floated this as an option, so depending on how much do dislike the extra pass, I can try to integrate it into the causality checks traversal.
